# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import os
import hashlib
import asyncio
import uuid
from datetime import datetime, timedelta
from iikoserver_client.api.session_management_api import SessionManagementApi
from iikoserver_client.api.corporation_management_api import CorporationManagementApi
from iikoserver_client import ApiClient
from iikoserver_client.configuration import Configuration
from iikoserver_client.api.employees_management_api import EmployeesManagementApi
from iikoserver_client.models.employee_xml import EmployeeXml
from iikoserver_client.models.public_external_data_xml import PublicExternalDataXml
from iikoserver_client.models.external_data_entry_xml import ExternalDataEntryXml
from iikoserver_client.models.attendance_xml import AttendanceXml
from iikoserver_client.models.attendances_xml import AttendancesXml
from iikoserver_client.models.attendance_types_xml import AttendanceTypesXml
from iikoserver_client.models.availabilities_xml import AvailabilitiesXml


class TestEmployeesManagementApi(unittest.IsolatedAsyncioTestCase):
    """EmployeesManagementApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        # Read credentials from env variables or set them directly
        self.server_url = os.environ.get("IIKO_SERVER_URL", None)
        self.login = os.environ.get("IIKO_SERVER_LOGIN", None)  # Replace with your login
        self.password = os.environ.get("IIKO_SERVER_PASSWORD", None)  # Replace with your password
        self.password_hash = hashlib.sha1(self.password.encode()).hexdigest()
        
        # Create configuration
        self.config = Configuration(host=self.server_url, debug=True)
        
        # Create API client with context manager support
        self.client = ApiClient(configuration=self.config)
        self.session_api = SessionManagementApi(api_client=self.client)
        await self.session_api.auth_post(login=self.login, var_pass=self.password_hash)
        self.api = EmployeesManagementApi(api_client=self.client)

        self.test_department_code = "1"
        self.test_department_id = "65430fca-3116-f1b6-0197-5488678d0012"
        self.test_department_name = "Мой ресторан"
    async def asyncTearDown(self) -> None:
        # Make sure to properly close all connections
        try:
            await self.session_api.logout_post()
        except Exception as e:
            print(f"Warning: logout failed: {e}")
        
        # Ensure client is closed properly
        await self.client.close()
        
        # Give event loop time to cleanup resources
        await asyncio.sleep(0.1)

    async def test_employees_get(self) -> None:
        """Test case for employees_get

        Список активных сотрудников
        """
        try:
            # Get all active employees
            result = await self.api.employees_get(
                include_deleted=False
            )
            for employee in result.employees:
                print(employee.name)
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'employees'))
            self.assertIsInstance(result.employees, list)
            
        except Exception as e:
            self.fail(f"Employees GET test failed with error: {str(e)}")

    async def test_employees_by_department_department_code_get(self) -> None:
        """Test case for employees_by_department_department_code_get

        Список сотрудников по подразделению
        """
        try:
            # Use first department code
            
            result = await self.api.employees_by_department_department_code_get(
                department_code=self.test_department_code,
                include_deleted=False
            )
            
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'employees'))
            self.assertIsInstance(result.employees, list)
            
        except Exception as e:
            self.fail(f"Employees by department GET test failed with error: {str(e)}")

    async def test_employees_by_id_employee_uuid_put(self) -> None:
        """Test case for employees_by_id_employee_uuid_put

        Добавить или заменить сотрудника (по Id)
        """
        employees = await self.api.employees_get(
            include_deleted=True,
            revision_from=0
        )
        integr_role_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
        codes = [employee.code for employee in employees.employees if employee.code and "test" in employee.code]
        if len(codes) > 0:
            test_employee_code = f"test_{max([int(code.split('_')[-1]) for code in codes]) + 1}"
        else:
            test_employee_code = "test_1"
        number = test_employee_code.split('_')[-1]
        try:
            # Create test employee data
            test_employee = EmployeeXml(
                code=test_employee_code,
                name=f"Test|Сотрудник API|0|{number}",
                firstName="Test",
                lastName="Сотрудник",
                departmentCodes=["3"],
                mainRoleCode=integr_role_employee.main_role_code,
                roleCodes=integr_role_employee.role_codes,
                login=f"test_login_{number}",
                supplier=False,
                employee=True,
                client=False,
                mainRoleId=integr_role_employee.main_role_id,
                rolesIds=integr_role_employee.roles_ids
            )
            
            # Create employee
            result = await self.api.employees_by_id_employee_uuid_put(
                employee_uuid=str(uuid.uuid4()),
                employee_xml=test_employee
            )
            
            self.assertIsNotNone(result)
            self.assertEqual(result.name, test_employee.name)
            
        except Exception as e:
            self.fail(f"Employees PUT by ID test failed with error: {str(e)}")

    async def test_employees_by_id_employee_uuid_get(self) -> None:
        """Test case for employees_by_id_employee_uuid_get

        Сотрудник по ID
        """
        try:
            # First create a test employee
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=0
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith(f"Test|Сотрудник API|")]
            last_employee = max(test_employees, key=lambda x: int(x.name.split('|')[-1]))
            if len(test_employees) == 0:
                self.fail("Test employee not found")
            test_employee = last_employee
            test_employee.name = f"Test|Сотрудник API|{int(test_employee.name.split('|')[-2]) + 1}|{test_employee.name.split('|')[-1]}"
            edited = await self.api.employees_by_id_employee_uuid_put(
                employee_uuid=test_employee.id,
                employee_xml=test_employee
            )
            
            # Get employee by ID
            result = await self.api.employees_by_id_employee_uuid_get(
                employee_uuid=edited.id
            )
            
            self.assertIsNotNone(result)
            self.assertEqual(result.id, edited.id)
            self.assertEqual(result.code, test_employee.code)
            
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=0
            )
            integr_role_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
            codes = [employee.code for employee in employees.employees if employee.code and "test" in employee.code]
            if len(codes) > 0:
                test_employee_code = f"test_{max([int(code.split('_')[-1]) for code in codes]) + 1}"
            else:
                test_employee_code = "test_1"
            number = test_employee_code.split('_')[-1]
            # Create test employee data
            test_employee = EmployeeXml(
                code=test_employee_code,
                name=f"Test|Сотрудник API|0|{number}",
                firstName="Test",
                lastName="Сотрудник",
                departmentCodes=["3"],
                mainRoleCode=integr_role_employee.main_role_code,
                roleCodes=integr_role_employee.role_codes,
                login=f"test_login_{number}",
                supplier=False,
                employee=True,
                client=False,
                mainRoleId=integr_role_employee.main_role_id,
                rolesIds=integr_role_employee.roles_ids
            )
            
            # Create employee
            result = await self.api.employees_by_id_employee_uuid_put(
                employee_uuid=str(uuid.uuid4()),
                employee_xml=test_employee
            )
            
            self.assertIsNotNone(result)
            self.assertEqual(result.name, test_employee.name)
    
        except Exception as e:
            self.fail(f"Employees GET by ID test failed with error: {str(e)}")

    async def test_employees_by_code_employee_code_get(self) -> None:
        """Test case for employees_by_code_employee_code_get

        Сотрудник по коду
        """
        try:
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=0
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith(f"Test|Сотрудник API|")]
            last_employee = max(test_employees, key=lambda x: int(x.name.split('|')[-1]))
            if len(test_employees) == 0:
                self.fail("Test employee not found")
            test_employee = last_employee
            
            # Get employee by code
            result = await self.api.employees_by_code_employee_code_get(
                employee_code=test_employee.code
            )
            
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'employees'))
            self.assertIsInstance(result.employees, list)
            self.assertTrue(len(result.employees) > 0)
            employee = result.employees[0]
            self.assertEqual(employee.code, test_employee.code)
            self.assertEqual(employee.name, test_employee.name)
            
        except Exception as e:
            self.fail(f"Employees GET by code test failed with error: {str(e)}")

    async def test_employees_search_get(self) -> None:
        """Test case for employees_search_get

        Поиск сотрудника
        """
        try:
            # Search with various criteria
            result = await self.api.employees_search_get(
                employee=True,
                include_deleted=False
            )
            
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'employees'))
            self.assertIsInstance(result.employees, list)
            
        except Exception as e:
            self.fail(f"Employees search GET test failed with error: {str(e)}")

    async def test_employees_by_id_employee_uuid_post(self) -> None:
        """Test case for employees_by_id_employee_uuid_post

        Изменить/добавить сотрудника (по id)
        """
        try:
            # First create a test employee
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=0
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith(f"Test|Сотрудник API|")]
            last_employee = max(test_employees, key=lambda x: int(x.name.split('|')[-1]))
            if len(test_employees) == 0:
                self.fail("Test employee not found")
            test_employee = last_employee
            new_name = f"Test|Сотрудник API|{int(test_employee.name.split('|')[-2]) + 1}|{test_employee.name.split('|')[-1]}"
            edited = await self.api.employees_by_id_employee_uuid_post(
                employee_uuid=test_employee.id,
                name=new_name
            )
            
            self.assertEqual(edited.id, test_employee.id)
            
        except Exception as e:
            self.fail(f"Employees POST by ID test failed with error: {str(e)}")

    async def test_employees_by_code_employee_code_put(self) -> None:
        """Test case for employees_by_code_employee_code_put

        Добавить сотрудника (по коду)
        """
        try:
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=0
            )
            integr_role_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
            codes = [employee.code for employee in employees.employees if employee.code and "test" in employee.code]
            if len(codes) > 0:
                test_employee_code = f"test_{max([int(code.split('_')[-1]) for code in codes]) + 1}"
            else:
                test_employee_code = "test_1"
            number = test_employee_code.split('_')[-1]
            
            # Create test employee data
            test_employee = EmployeeXml(
                code=test_employee_code,
                name=f"Test|Сотрудник API|0|{number}",
                firstName="Test",
                lastName="Сотрудник",
                departmentCodes=["3"],
                mainRoleCode=integr_role_employee.main_role_code,
                roleCodes=integr_role_employee.role_codes,
                login=f"test_login_{number}",
                supplier=False,
                employee=True,
                client=False,
                mainRoleId=integr_role_employee.main_role_id,
                rolesIds=integr_role_employee.roles_ids
            )
            
            # Create employee by code
            result = await self.api.employees_by_code_employee_code_put(
                employee_code=test_employee_code,
                employee_xml=test_employee
            )
            
            self.assertIsNotNone(result)
            self.assertEqual(result.code, test_employee_code)
            self.assertEqual(result.name, test_employee.name)
            
        except Exception as e:
            self.fail(f"Employees PUT by code test failed with error: {str(e)}")

    async def test_employees_by_id_employee_uuid_delete(self) -> None:
        """Test case for employees_by_id_employee_uuid_delete

        Удалить сотрудника
        """
        try:
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            tests = [employee for employee in employees.employees if employee.name.startswith(f"Test|Сотрудник API|")]
            last_employee = max(tests, key=lambda x: int(x.name.split('|')[-1]))
            
            
            # Delete the employee
            response = await self.api.employees_by_id_employee_uuid_delete(
                employee_uuid=last_employee.id
            )
                
        except Exception as e:
            self.fail(f"Employees DELETE test failed with error: {str(e)}")

    async def test_employees_roles_get(self) -> None:
        """Test case for employees_roles_get

        Список должностей
        """
        try:
            # Get all employee roles
            result = await self.api.employees_roles_get()
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'role'))
            self.assertIsInstance(result.role, list)
            
        except Exception as e:
            self.fail(f"Employee roles GET test failed with error: {str(e)}")

    async def test_employees_salary_get(self) -> None:
        """Test case for employees_salary_get

        Список окладов
        """
        try:
            # Get all employee salaries
            result = await self.api.employees_salary_get()
            
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'salary'))
            self.assertIsInstance(result.salary, list)
            
        except Exception as e:
            self.fail(f"Employee salaries GET test failed with error: {str(e)}")

    async def test_employees_salary_by_id_employee_uuid_get(self) -> None:
        """Test case for employees_salary_by_id_employee_uuid_get

        Текущий оклад сотрудника
        """
        try:
            # Get existing employees to use one for testing
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                test_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
                # Get current salary for the employee
                result = await self.api.employees_salary_by_id_employee_uuid_get(
                    employee_uuid=test_employee.id
                )
                
                self.assertIsNotNone(result)
                if hasattr(result, 'employeeId') and result.employeeId:
                    self.assertEqual(result.employeeId, test_employee.id)
            
        except Exception as e:
            self.fail(f"Employee salary by ID GET test failed with error: {str(e)}")

    async def test_employees_salary_by_id_employee_uuid_date_get(self) -> None:
        """Test case for employees_salary_by_id_employee_uuid_date_get

        Оклад сотрудника на дату
        """
        try:
            # Get existing employees to use one for testing
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                test_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
                test_date = datetime.now().date()
                
                # Get salary for the employee on specific date
                result = await self.api.employees_salary_by_id_employee_uuid_date_get(
                    employee_uuid=test_employee.id,
                    var_date=test_date
                )
                
                self.assertIsNotNone(result)
                if hasattr(result, 'employeeId') and result.employeeId:
                    self.assertEqual(result.employeeId, test_employee.id)
            
        except Exception as e:
            self.fail(f"Employee salary by ID and date GET test failed with error: {str(e)}")

    async def test_employees_salary_by_id_employee_uuid_date_post(self) -> None:
        """Test case for employees_salary_by_id_employee_uuid_date_post

        Установить оклад сотрудника
        """
        try:
            # Get existing test employees
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=-1
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith(f"Test|Сотрудник API|")]
            
            if len(test_employees) > 0:
                test_employee = test_employees[0]
                test_date = datetime.now().date()
                test_payment = 50000.0
                
                # Set salary for the test employee
                result = await self.api.employees_salary_by_id_employee_uuid_date_post(
                    employee_uuid=test_employee.id,
                    var_date=test_date,
                    payment=test_payment
                )
                
                self.assertIsNotNone(result)
                if hasattr(result, 'payment') and result.payment:
                    self.assertEqual(result.payment, test_payment)
                if hasattr(result, 'employeeId') and result.employeeId:
                    self.assertEqual(result.employeeId, test_employee.id)
            
        except Exception as e:
            self.fail(f"Employee salary POST test failed with error: {str(e)}")

    async def test_employees_schedule_types_get(self) -> None:
        """Test case for employees_schedule_types_get

        Получить типы смен
        """
        try:
            # Get all schedule types
            result = await self.api.employees_schedule_types_get()
            print(result)
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'employee_schedule_types'))
            self.assertIsInstance(result.employee_schedule_types, list)
            
        except Exception as e:
            self.fail(f"Employee schedule types GET test failed with error: {str(e)}")

    async def test_employees_schedule_get(self) -> None:
        """Test case for employees_schedule_get

        Получить смены
        """
        try:
            # Get schedules for a date range
            from_date = datetime.now().date()
            to_date = datetime.now().date()
            
            result = await self.api.employees_schedule_get(
                var_from=from_date,
                to=to_date,
                with_payment_details=False
            )
            print(result)
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'schedule'))
            self.assertIsInstance(result.schedule, list)
            
        except Exception as e:
            self.fail(f"Employee schedules GET test failed with error: {str(e)}")

    async def test_employees_schedule_by_employee_employee_uuid_get(self) -> None:
        """Test case for employees_schedule_by_employee_employee_uuid_get

        Получить смены по сотруднику
        """
        try:
            # Get existing employees to use one for testing
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                test_employee = employees.employees[0]
                from_date = datetime.now().date()
                to_date = datetime.now().date()
                
                # Get schedules for the employee
                result = await self.api.employees_schedule_by_employee_employee_uuid_get(
                    employee_uuid=test_employee.id,
                    var_from=from_date,
                    to=to_date,
                    with_payment_details=False
                )
                
                self.assertIsNotNone(result)
                self.assertTrue(hasattr(result, 'schedule'))
                self.assertIsInstance(result.schedule, list)
            
        except Exception as e:
            self.fail(f"Employee schedules by employee GET test failed with error: {str(e)}")

    async def test_employees_schedule_by_department_department_code_get(self) -> None:
        """Test case for employees_schedule_by_department_department_code_get

        Получить смены по подразделению
        """
        try:
            from_date = datetime.now().date()
            to_date = datetime.now().date()
            
            # Get schedules for department
            result = await self.api.employees_schedule_by_department_department_code_get(
                department_code=self.test_department_code,
                var_from=from_date,
                to=to_date,
                with_payment_details=False
            )
            
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'schedule'))
            self.assertIsInstance(result.schedule, list)
            
        except Exception as e:
            self.fail(f"Employee schedules by department GET test failed with error: {str(e)}")

    async def test_employees_schedule_create_post(self) -> None:
        """Test case for employees_schedule_create_post

        Создать смену
        """
        try:
            # Get existing test employees and roles
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=-1
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith("Test|Сотрудник API|")]
            
            if len(test_employees) > 0:
                test_employee = test_employees[0]
                
                # Get available roles
                roles = await self.api.employees_roles_get()
                if len(roles.role) > 0:
                    test_role = roles.role[0]
                    
                    # Get schedule types
                    schedule_types = await self.api.employees_schedule_types_get()
                    if len(schedule_types.employee_schedule_types) > 0:
                        test_schedule_type = schedule_types.employee_schedule_types[0]
                        
                        # Create schedule data
                        from iikoserver_client.models.schedule_xml import ScheduleXml
                        
                        schedule_data = ScheduleXml(
                            employeeId=test_employee.id,
                            roleId=test_role.id,
                            scheduleTypeCode=test_schedule_type.code,
                            dateFrom=datetime.now().isoformat(),
                            dateTo=(datetime.now().replace(hour=min(datetime.now().hour + 8, 23))).isoformat(),
                            nonPaidMinutes=0,
                            departmentId=self.test_department_id,
                            departmentName=self.test_department_name
                        )
                        
                        # Create schedule
                        result = await self.api.employees_schedule_create_post(
                            schedule_xml=schedule_data
                        )
                        
                        self.assertIsNotNone(result)
                        self.assertIsNotNone(result.id)  # Should have generated ID
                        self.assertEqual(result.employee_id, test_employee.id)
            
        except Exception as e:
            self.fail(f"Employee schedule create POST test failed with error: {str(e)}")

    async def test_employees_schedule_update_post(self) -> None:
        """Test case for employees_schedule_update_post

        Обновить смену
        """
        try:
            # First create a schedule to update
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=-1
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith("Test|Сотрудник API|")]
            
            if len(test_employees) > 0:
                test_employee = test_employees[0]
                
                # Get available roles and schedule types
                roles = await self.api.employees_roles_get()
                schedule_types = await self.api.employees_schedule_types_get()
                
                if len(roles.role) > 0 and len(schedule_types.employee_schedule_types) > 0:
                    test_role = roles.role[0]
                    test_schedule_type = schedule_types.employee_schedule_types[0]
                    
                    # Create schedule data
                    from iikoserver_client.models.schedule_xml import ScheduleXml
                    
                    schedule_data = ScheduleXml(
                        employeeId=test_employee.id,
                        roleId=test_role.id,
                        scheduleTypeCode=test_schedule_type.code,
                        dateFrom=datetime.now().isoformat(),
                        dateTo=(datetime.now().replace(hour=min(datetime.now().hour + 6, 23))).isoformat(),
                        nonPaidMinutes=30,
                        departmentId=self.test_department_id,
                        departmentName=self.test_department_name
                    )
                    
                    # Create schedule first
                    created_schedule = await self.api.employees_schedule_create_post(
                        schedule_xml=schedule_data
                    )
                    
                    # Update the created schedule
                    created_schedule.non_paid_minutes = 60  # Change non-paid minutes
                    created_schedule.date_to = (datetime.now().replace(hour=min(datetime.now().hour + 8, 23))).isoformat()
                    
                    # Update schedule
                    result = await self.api.employees_schedule_update_post(
                        schedule_xml=created_schedule
                    )
                    
                    self.assertIsNotNone(result)
                    self.assertEqual(result.employee_id, test_employee.id)
                    self.assertEqual(result.non_paid_minutes, 60)
            
        except Exception as e:
            self.fail(f"Employee schedule update POST test failed with error: {str(e)}")

    async def test_employees_schedule_by_id_schedule_uuid_delete(self) -> None:
        """Test case for employees_schedule_by_id_schedule_uuid_delete

        Удалить смену
        """
        try:
            # First create a schedule to delete
            employees = await self.api.employees_get(
                include_deleted=True,
                revision_from=-1
            )
            test_employees = [employee for employee in employees.employees if employee.name.startswith("Test|Сотрудник API|")]
            
            if len(test_employees) > 0:
                test_employee = test_employees[0]
                
                # Get available roles and schedule types
                roles = await self.api.employees_roles_get()
                schedule_types = await self.api.employees_schedule_types_get()
                
                if len(roles.role) > 0 and len(schedule_types.employee_schedule_types) > 0:
                    test_role = roles.role[0]
                    test_schedule_type = schedule_types.employee_schedule_types[0]
                    
                    # Create schedule data
                    from iikoserver_client.models.schedule_xml import ScheduleXml
                    
                    schedule_data = ScheduleXml(
                        employeeId=test_employee.id,
                        roleId=test_role.id,
                        scheduleTypeCode=test_schedule_type.code,
                        dateFrom=datetime.now().isoformat(),
                        dateTo=(datetime.now().replace(hour=min(datetime.now().hour + 4, 23))).isoformat(),
                        nonPaidMinutes=0,
                        departmentId=self.test_department_id,
                        departmentName=self.test_department_name
                    )
                    
                    # Create schedule first
                    created_schedule = await self.api.employees_schedule_create_post(
                        schedule_xml=schedule_data
                    )
                    
                    # Delete the created schedule
                    result = await self.api.employees_schedule_by_id_schedule_uuid_delete(
                        schedule_uuid=created_schedule.id
                    )
                    
                    self.assertIsNotNone(result)
                    self.assertEqual(result.id, created_schedule.id)
                    self.assertEqual(result.employee_id, test_employee.id)
            
        except Exception as e:
            self.fail(f"Employee schedule delete test failed with error: {str(e)}")

    async def test_employees_attendance_types_get(self) -> None:
        """Test case for employees_attendance_types_get

        Получить типы явок
        """
        try:
            # Get attendance types
            result = await self.api.employees_attendance_types_get(
                include_deleted=False,
                revision_from=-1
            )
            print(result)
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'attendance_type'))
            self.assertIsInstance(result.attendance_type, list)
            
            if len(result.attendance_type) > 0:
                attendance_type = result.attendance_type[0]
                self.assertIsNotNone(attendance_type.id)
                self.assertIsNotNone(attendance_type.code)
                self.assertIsNotNone(attendance_type.name)
            
        except Exception as e:
            self.fail(f"Employee attendance types GET test failed with error: {str(e)}")

    async def test_employees_attendance_get(self) -> None:
        """Test case for employees_attendance_get

        Получить явки
        """
        try:
            from_date = (datetime.now() - timedelta(days=30)).date()
            to_date = datetime.now().date()
            
            # Get attendances
            result = await self.api.employees_attendance_get(
                var_from=from_date,
                to=to_date,
                with_payment_details=True,
                revision_from=-1
            )
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'attendances'))
            self.assertIsInstance(result.attendances, list)
            
        except Exception as e:
            self.fail(f"Employee attendance GET test failed with error: {str(e)}")

    async def test_employees_attendance_by_employee_employee_uuid_get(self) -> None:
        """Test case for employees_attendance_by_employee_employee_uuid_get

        Получить явки сотрудника
        """
        try:
            # Get a test employee first
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                #get employee with name user
                test_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
                if not test_employee:
                    self.fail("Test employee not found")
                
                from_date = (datetime.now() - timedelta(days=7)).date()
                to_date = datetime.now().date()
                
                # Get attendances for specific employee
                result = await self.api.employees_attendance_by_employee_employee_uuid_get(
                    employee_uuid=test_employee.id,
                    var_from=from_date,
                    to=to_date,
                    with_payment_details=False,
                    revision_from=-1
                )
                
                self.assertIsNotNone(result)
                self.assertTrue(hasattr(result, 'attendances'))
                self.assertIsInstance(result.attendances, list)
            
        except Exception as e:
            self.fail(f"Employee attendance by employee GET test failed with error: {str(e)}")

    async def test_employees_attendance_by_department_department_code_get(self) -> None:
        """Test case for employees_attendance_by_department_department_code_get

        Получить явки по подразделению
        """
        try:
            from_date = (datetime.now() - timedelta(days=7)).date()
            to_date = datetime.now().date()
            
            # Get attendances for department
            result = await self.api.employees_attendance_by_department_department_code_get(
                department_code=self.test_department_code,
                var_from=from_date,
                to=to_date,
                with_payment_details=False,
                revision_from=-1
            )
            print(result)
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'attendances'))
            self.assertIsInstance(result.attendances, list)
            
        except Exception as e:
            self.fail(f"Employee attendance by department GET test failed with error: {str(e)}")

    async def test_employees_attendance_department_department_id_get(self) -> None:
        """Test case for employees_attendance_department_department_id_get

        Получить явки по ID подразделения
        """
        try:
            from_date = (datetime.now() - timedelta(days=7)).date()
            to_date = datetime.now().date()
            
            # Get attendances for department by ID
            result = await self.api.employees_attendance_department_department_id_get(
                department_id=self.test_department_id,
                var_from=from_date,
                to=to_date,
                with_payment_details=False,
                revision_from=-1
            )
            print(result)
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'attendances'))
            self.assertIsInstance(result.attendances, list)

        except Exception as e:
            self.fail(f"Employee attendance by department ID GET test failed with error: {str(e)}")

    async def test_employees_attendance_create_post(self) -> None:
        """Test case for employees_attendance_create_post

        Создать явку
        """
        try:
            # Get a test employee
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                test_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
                if not test_employee:
                    self.fail("Test employee not found")
                
                # Get attendance types
                attendance_types = await self.api.employees_attendance_types_get(
                    include_deleted=False,
                    revision_from=-1
                )
                
                if len(attendance_types.attendance_type) > 0:
                    test_attendance_type = attendance_types.attendance_type[0]
                    
                    # Create attendance data
                    start_time = datetime.now().replace(minute=0, second=0, microsecond=0)
                    end_time = start_time + timedelta(hours=8)
                    
                    attendance_data = AttendanceXml(
                        employeeId=test_employee.id,
                        roleId=test_employee.main_role_id if test_employee.main_role_id else None,
                        attendanceTypeId=test_attendance_type.id,
                        attendanceType=test_attendance_type.code,
                        dateFrom=start_time.isoformat(),
                        dateTo=end_time.isoformat(),
                        departmentId=self.test_department_id,
                        departmentName=self.test_department_name,
                        comment="Test attendance created by API"
                    )
                    
                    # Create attendance
                    result = await self.api.employees_attendance_create_post(
                        attendance_xml=attendance_data
                    )
                    
                    self.assertIsNotNone(result)
                    self.assertIsNotNone(result.id)  # Should have generated ID
                    self.assertEqual(result.employee_id, test_employee.id)
                    self.assertEqual(result.department_id, self.test_department_id)
            
        except Exception as e:
            self.fail(f"Employee attendance create POST test failed with error: {str(e)}")

    async def test_employees_attendance_update_post(self) -> None:
        """Test case for employees_attendance_update_post

        Обновить явку
        """
        try:
            # First create an attendance to update
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                test_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
                if not test_employee:
                    self.fail("Test employee not found")
                
                # Get attendances
                from_date = (datetime.now() - timedelta(days=7)).date()
                to_date = datetime.now().date()

                result = await self.api.employees_attendance_by_employee_employee_uuid_get(
                    employee_uuid=test_employee.id,
                    var_from=from_date,
                    to=to_date,
                    with_payment_details=False,
                    revision_from=-1
                )

                attendance = result.attendances[0]
                attendance.comment = "Updated test attendance"
                
                # Update attendance
                result = await self.api.employees_attendance_update_post(
                    attendance_xml=attendance
                )
                
                self.assertIsNotNone(result)
                self.assertEqual(result.employee_id, test_employee.id)
                self.assertEqual(result.comment, "Updated test attendance")
            
        except Exception as e:
            self.fail(f"Employee attendance update POST test failed with error: {str(e)}")

    async def test_employees_attendance_by_id_attendance_uuid_delete(self) -> None:
        """Test case for employees_attendance_by_id_attendance_uuid_delete

        Удалить явку
        """
        try:
            # First create an attendance to delete
            employees = await self.api.employees_get(
                include_deleted=False,
                revision_from=-1
            )
            
            if len(employees.employees) > 0:
                test_employee = next((employee for employee in employees.employees if employee.name == "user"), None)
                if not test_employee:
                    self.fail("Test employee not found")
                
                from_date = (datetime.now() - timedelta(days=7)).date()
                to_date = datetime.now().date()

                result = await self.api.employees_attendance_by_employee_employee_uuid_get(
                    employee_uuid=test_employee.id,
                    var_from=from_date,
                    to=to_date,
                    with_payment_details=False,
                    revision_from=-1
                )
                results = []
                for attendance in result.attendances:
                    results.append(await self.api.employees_attendance_by_id_attendance_uuid_delete(
                        attendance_uuid=attendance.id
                    ))
                
                self.assertIsNotNone(results)
                self.assertEqual(len(results), len(result.attendances))
        
        except Exception as e:
            self.fail(f"Employee attendance delete test failed with error: {str(e)}")

    async def test_employees_availability_list_get(self) -> None:
        """Test case for employees_availability_list_get

        Получить доступность сотрудников
        """
        try:
            from_date = datetime.now().date()
            to_date = (datetime.now() + timedelta(days=7)).date()
            
            # Get employees availability
            result = await self.api.employees_availability_list_get(
                var_from=from_date,
                to=to_date,
                department=[self.test_department_id],
                role=None,
                user=None
            )
            
            self.assertIsNotNone(result)
            self.assertTrue(hasattr(result, 'availability'))
            self.assertIsInstance(result.availability, list)
            
            if len(result.availability) > 0:
                availability = result.availability[0]
                self.assertIsNotNone(availability.employee_id)
                self.assertIsNotNone(availability.date_from)
                self.assertIsNotNone(availability.date_to)
            
        except Exception as e:
            self.fail(f"Employee availability list GET test failed with error: {str(e)}")


if __name__ == '__main__':
    unittest.main() 