# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json
import os
import hashlib
import asyncio
import unittest


from iikoserver_client.api.supplers_management_api import SupplersManagementApi
from iikoserver_client.api.session_management_api import SessionManagementApi
from iikoserver_client import ApiClient
from iikoserver_client.configuration import Configuration

class TestSupplersManagementApi(unittest.IsolatedAsyncioTestCase):
    """SupplersManagementApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        # Read credentials from env variables or set them directly
        self.server_url = os.environ.get("IIKO_SERVER_URL", None)
        self.login = os.environ.get("IIKO_SERVER_LOGIN", None)  # Replace with your login
        self.password = os.environ.get("IIKO_SERVER_PASSWORD", None)  # Replace with your password
        self.password_hash = hashlib.sha1(self.password.encode()).hexdigest()
        
        # Create configuration
        self.config = Configuration(host=self.server_url, debug=True)
        
        # Create API client with context manager support
        self.client = ApiClient(configuration=self.config)
        self.session_api = SessionManagementApi(api_client=self.client)
        await self.session_api.auth_post(login=self.login, var_pass=self.password_hash)
        self.api = SupplersManagementApi(api_client=self.client)

    async def asyncTearDown(self) -> None:
        # Make sure to properly close all connections
        try:
            await self.session_api.logout_post()
        except Exception as e:
            print(f"Warning: logout failed: {e}")
        
        # Ensure client is closed properly
        await self.client.close()
        
        # Give event loop time to cleanup resources
        await asyncio.sleep(0.1)

    async def test_suppliers_get(self) -> None:
        """Test case for suppliers_get

        Список поставщиков
        """
        try:
            response = await self.api.suppliers_get()
            self.assertIsNotNone(response)
            self.assertTrue(len(response.employees) > 0)
            print(json.dumps(response.to_dict(), indent=4, ensure_ascii=False))
        except Exception as e:
            self.fail(f"Suppliers GET test failed with error: {str(e)}")

    async def test_suppliers_search_get(self) -> None:
        """Test case for suppliers_search_get

        Поиск поставщика
        """
        try:
            response = await self.api.suppliers_search_get(name="Test*")
            self.assertIsNotNone(response)
            self.assertTrue(len(response.employees) > 0)
            print(json.dumps(response.to_dict(), indent=4, ensure_ascii=False))
        except Exception as e:
            self.fail(f"Suppliers search GET test failed with error: {str(e)}")

    async def test_suppliers_code_pricelist_get(self) -> None:
        """Test case for suppliers_code_pricelist_get

        Прайс-лист поставщика
        """
        try:
            response = await self.api.suppliers_code_pricelist_get(code="2")
            self.assertIsNotNone(response)
            self.assertTrue(len(response.supplier_price_list_item_dtoes) > 0)
            print(json.dumps(response.to_dict(), indent=4, ensure_ascii=False))
        except Exception as e:
            self.fail(f"Suppliers code pricelist GET test failed with error: {str(e)}")


if __name__ == '__main__':
    unittest.main()
