# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from iikoserver_client.models.quick_menu_create_dto import QuickMenuCreateDto
from iikoserver_client.models.quick_menu_delete_dto import QuickMenuDeleteDto
from iikoserver_client.models.quick_menu_dto import QuickMenuDto
from iikoserver_client.models.quick_menu_operation_response_scheme import QuickMenuOperationResponseScheme
from iikoserver_client.models.quick_menu_update_dto import QuickMenuUpdateDto

from iikoserver_client.api_client import ApiClient, RequestSerialized
from iikoserver_client.api_response import ApiResponse
from iikoserver_client.rest import RESTResponseType


class FastMenuManagementApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def v2_entities_quick_labels_delete_post(
        self,
        quick_menu_delete_dto: Annotated[QuickMenuDeleteDto, Field(description="UUID быстрого меню для удаления")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QuickMenuOperationResponseScheme:
        """Удаление быстрого меню

        Помечает быстрое меню как удаленное

        :param quick_menu_delete_dto: UUID быстрого меню для удаления (required)
        :type quick_menu_delete_dto: QuickMenuDeleteDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_delete_post_serialize(
            quick_menu_delete_dto=quick_menu_delete_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def v2_entities_quick_labels_delete_post_with_http_info(
        self,
        quick_menu_delete_dto: Annotated[QuickMenuDeleteDto, Field(description="UUID быстрого меню для удаления")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QuickMenuOperationResponseScheme]:
        """Удаление быстрого меню

        Помечает быстрое меню как удаленное

        :param quick_menu_delete_dto: UUID быстрого меню для удаления (required)
        :type quick_menu_delete_dto: QuickMenuDeleteDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_delete_post_serialize(
            quick_menu_delete_dto=quick_menu_delete_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def v2_entities_quick_labels_delete_post_without_preload_content(
        self,
        quick_menu_delete_dto: Annotated[QuickMenuDeleteDto, Field(description="UUID быстрого меню для удаления")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Удаление быстрого меню

        Помечает быстрое меню как удаленное

        :param quick_menu_delete_dto: UUID быстрого меню для удаления (required)
        :type quick_menu_delete_dto: QuickMenuDeleteDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_delete_post_serialize(
            quick_menu_delete_dto=quick_menu_delete_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v2_entities_quick_labels_delete_post_serialize(
        self,
        quick_menu_delete_dto,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if quick_menu_delete_dto is not None:
            _body_params = quick_menu_delete_dto


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'iikoCookieAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v2/entities/quickLabels/delete',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def v2_entities_quick_labels_list_get(
        self,
        include_deleted: Annotated[Optional[StrictBool], Field(description="Включать ли удаленные быстрые меню")] = None,
        revision_from: Annotated[Optional[StrictInt], Field(description="Номер ревизии, начиная с которой необходимо отфильтровать сущности")] = None,
        id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID быстрых меню для фильтрации")] = None,
        department_id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID подразделений для фильтрации")] = None,
        section_id: Annotated[Optional[List[Optional[StrictStr]]], Field(description="Список UUID отделений для фильтрации (может содержать null)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[QuickMenuDto]:
        """Получение списка быстрых меню

        Возвращает список быстрых меню с фильтрацией по различным параметрам

        :param include_deleted: Включать ли удаленные быстрые меню
        :type include_deleted: bool
        :param revision_from: Номер ревизии, начиная с которой необходимо отфильтровать сущности
        :type revision_from: int
        :param id: Список UUID быстрых меню для фильтрации
        :type id: List[str]
        :param department_id: Список UUID подразделений для фильтрации
        :type department_id: List[str]
        :param section_id: Список UUID отделений для фильтрации (может содержать null)
        :type section_id: List[Optional[str]]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_list_get_serialize(
            include_deleted=include_deleted,
            revision_from=revision_from,
            id=id,
            department_id=department_id,
            section_id=section_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[QuickMenuDto]",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def v2_entities_quick_labels_list_get_with_http_info(
        self,
        include_deleted: Annotated[Optional[StrictBool], Field(description="Включать ли удаленные быстрые меню")] = None,
        revision_from: Annotated[Optional[StrictInt], Field(description="Номер ревизии, начиная с которой необходимо отфильтровать сущности")] = None,
        id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID быстрых меню для фильтрации")] = None,
        department_id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID подразделений для фильтрации")] = None,
        section_id: Annotated[Optional[List[Optional[StrictStr]]], Field(description="Список UUID отделений для фильтрации (может содержать null)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[QuickMenuDto]]:
        """Получение списка быстрых меню

        Возвращает список быстрых меню с фильтрацией по различным параметрам

        :param include_deleted: Включать ли удаленные быстрые меню
        :type include_deleted: bool
        :param revision_from: Номер ревизии, начиная с которой необходимо отфильтровать сущности
        :type revision_from: int
        :param id: Список UUID быстрых меню для фильтрации
        :type id: List[str]
        :param department_id: Список UUID подразделений для фильтрации
        :type department_id: List[str]
        :param section_id: Список UUID отделений для фильтрации (может содержать null)
        :type section_id: List[Optional[str]]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_list_get_serialize(
            include_deleted=include_deleted,
            revision_from=revision_from,
            id=id,
            department_id=department_id,
            section_id=section_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[QuickMenuDto]",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def v2_entities_quick_labels_list_get_without_preload_content(
        self,
        include_deleted: Annotated[Optional[StrictBool], Field(description="Включать ли удаленные быстрые меню")] = None,
        revision_from: Annotated[Optional[StrictInt], Field(description="Номер ревизии, начиная с которой необходимо отфильтровать сущности")] = None,
        id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID быстрых меню для фильтрации")] = None,
        department_id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID подразделений для фильтрации")] = None,
        section_id: Annotated[Optional[List[Optional[StrictStr]]], Field(description="Список UUID отделений для фильтрации (может содержать null)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Получение списка быстрых меню

        Возвращает список быстрых меню с фильтрацией по различным параметрам

        :param include_deleted: Включать ли удаленные быстрые меню
        :type include_deleted: bool
        :param revision_from: Номер ревизии, начиная с которой необходимо отфильтровать сущности
        :type revision_from: int
        :param id: Список UUID быстрых меню для фильтрации
        :type id: List[str]
        :param department_id: Список UUID подразделений для фильтрации
        :type department_id: List[str]
        :param section_id: Список UUID отделений для фильтрации (может содержать null)
        :type section_id: List[Optional[str]]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_list_get_serialize(
            include_deleted=include_deleted,
            revision_from=revision_from,
            id=id,
            department_id=department_id,
            section_id=section_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[QuickMenuDto]",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v2_entities_quick_labels_list_get_serialize(
        self,
        include_deleted,
        revision_from,
        id,
        department_id,
        section_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'id': 'multi',
            'departmentId': 'multi',
            'sectionId': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if include_deleted is not None:
            
            _query_params.append(('includeDeleted', include_deleted))
            
        if revision_from is not None:
            
            _query_params.append(('revisionFrom', revision_from))
            
        if id is not None:
            
            _query_params.append(('id', id))
            
        if department_id is not None:
            
            _query_params.append(('departmentId', department_id))
            
        if section_id is not None:
            
            _query_params.append(('sectionId', section_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'iikoCookieAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2/entities/quickLabels/list',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def v2_entities_quick_labels_list_post(
        self,
        include_deleted: Annotated[Optional[StrictBool], Field(description="Включать ли удаленные быстрые меню")] = None,
        revision_from: Annotated[Optional[StrictInt], Field(description="Номер ревизии, начиная с которой необходимо отфильтровать сущности")] = None,
        id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID быстрых меню для фильтрации")] = None,
        department_id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID подразделений для фильтрации")] = None,
        section_id: Annotated[Optional[List[Optional[StrictStr]]], Field(description="Список UUID отделений для фильтрации (может содержать null)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[QuickMenuDto]:
        """Получение списка быстрых меню (расширенный)

        Возвращает список быстрых меню с расширенными возможностями фильтрации через form data

        :param include_deleted: Включать ли удаленные быстрые меню
        :type include_deleted: bool
        :param revision_from: Номер ревизии, начиная с которой необходимо отфильтровать сущности
        :type revision_from: int
        :param id: Список UUID быстрых меню для фильтрации
        :type id: List[str]
        :param department_id: Список UUID подразделений для фильтрации
        :type department_id: List[str]
        :param section_id: Список UUID отделений для фильтрации (может содержать null)
        :type section_id: List[Optional[str]]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_list_post_serialize(
            include_deleted=include_deleted,
            revision_from=revision_from,
            id=id,
            department_id=department_id,
            section_id=section_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[QuickMenuDto]",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def v2_entities_quick_labels_list_post_with_http_info(
        self,
        include_deleted: Annotated[Optional[StrictBool], Field(description="Включать ли удаленные быстрые меню")] = None,
        revision_from: Annotated[Optional[StrictInt], Field(description="Номер ревизии, начиная с которой необходимо отфильтровать сущности")] = None,
        id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID быстрых меню для фильтрации")] = None,
        department_id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID подразделений для фильтрации")] = None,
        section_id: Annotated[Optional[List[Optional[StrictStr]]], Field(description="Список UUID отделений для фильтрации (может содержать null)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[QuickMenuDto]]:
        """Получение списка быстрых меню (расширенный)

        Возвращает список быстрых меню с расширенными возможностями фильтрации через form data

        :param include_deleted: Включать ли удаленные быстрые меню
        :type include_deleted: bool
        :param revision_from: Номер ревизии, начиная с которой необходимо отфильтровать сущности
        :type revision_from: int
        :param id: Список UUID быстрых меню для фильтрации
        :type id: List[str]
        :param department_id: Список UUID подразделений для фильтрации
        :type department_id: List[str]
        :param section_id: Список UUID отделений для фильтрации (может содержать null)
        :type section_id: List[Optional[str]]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_list_post_serialize(
            include_deleted=include_deleted,
            revision_from=revision_from,
            id=id,
            department_id=department_id,
            section_id=section_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[QuickMenuDto]",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def v2_entities_quick_labels_list_post_without_preload_content(
        self,
        include_deleted: Annotated[Optional[StrictBool], Field(description="Включать ли удаленные быстрые меню")] = None,
        revision_from: Annotated[Optional[StrictInt], Field(description="Номер ревизии, начиная с которой необходимо отфильтровать сущности")] = None,
        id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID быстрых меню для фильтрации")] = None,
        department_id: Annotated[Optional[List[StrictStr]], Field(description="Список UUID подразделений для фильтрации")] = None,
        section_id: Annotated[Optional[List[Optional[StrictStr]]], Field(description="Список UUID отделений для фильтрации (может содержать null)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Получение списка быстрых меню (расширенный)

        Возвращает список быстрых меню с расширенными возможностями фильтрации через form data

        :param include_deleted: Включать ли удаленные быстрые меню
        :type include_deleted: bool
        :param revision_from: Номер ревизии, начиная с которой необходимо отфильтровать сущности
        :type revision_from: int
        :param id: Список UUID быстрых меню для фильтрации
        :type id: List[str]
        :param department_id: Список UUID подразделений для фильтрации
        :type department_id: List[str]
        :param section_id: Список UUID отделений для фильтрации (может содержать null)
        :type section_id: List[Optional[str]]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_list_post_serialize(
            include_deleted=include_deleted,
            revision_from=revision_from,
            id=id,
            department_id=department_id,
            section_id=section_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[QuickMenuDto]",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v2_entities_quick_labels_list_post_serialize(
        self,
        include_deleted,
        revision_from,
        id,
        department_id,
        section_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'id': 'csv',
            'departmentId': 'csv',
            'sectionId': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        if include_deleted is not None:
            _form_params.append(('includeDeleted', include_deleted))
        if revision_from is not None:
            _form_params.append(('revisionFrom', revision_from))
        if id is not None:
            _form_params.append(('id', id))
        if department_id is not None:
            _form_params.append(('departmentId', department_id))
        if section_id is not None:
            _form_params.append(('sectionId', section_id))
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/x-www-form-urlencoded'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'iikoCookieAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v2/entities/quickLabels/list',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def v2_entities_quick_labels_save_post(
        self,
        quick_menu_create_dto: Annotated[QuickMenuCreateDto, Field(description="Данные для создания быстрого меню")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QuickMenuOperationResponseScheme:
        """Создание быстрого меню

        Создает новое быстрое меню с указанными параметрами и ячейками

        :param quick_menu_create_dto: Данные для создания быстрого меню (required)
        :type quick_menu_create_dto: QuickMenuCreateDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_save_post_serialize(
            quick_menu_create_dto=quick_menu_create_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def v2_entities_quick_labels_save_post_with_http_info(
        self,
        quick_menu_create_dto: Annotated[QuickMenuCreateDto, Field(description="Данные для создания быстрого меню")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QuickMenuOperationResponseScheme]:
        """Создание быстрого меню

        Создает новое быстрое меню с указанными параметрами и ячейками

        :param quick_menu_create_dto: Данные для создания быстрого меню (required)
        :type quick_menu_create_dto: QuickMenuCreateDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_save_post_serialize(
            quick_menu_create_dto=quick_menu_create_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def v2_entities_quick_labels_save_post_without_preload_content(
        self,
        quick_menu_create_dto: Annotated[QuickMenuCreateDto, Field(description="Данные для создания быстрого меню")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Создание быстрого меню

        Создает новое быстрое меню с указанными параметрами и ячейками

        :param quick_menu_create_dto: Данные для создания быстрого меню (required)
        :type quick_menu_create_dto: QuickMenuCreateDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_save_post_serialize(
            quick_menu_create_dto=quick_menu_create_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v2_entities_quick_labels_save_post_serialize(
        self,
        quick_menu_create_dto,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if quick_menu_create_dto is not None:
            _body_params = quick_menu_create_dto


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'iikoCookieAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v2/entities/quickLabels/save',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def v2_entities_quick_labels_update_post(
        self,
        quick_menu_update_dto: Annotated[QuickMenuUpdateDto, Field(description="Данные для обновления быстрого меню")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QuickMenuOperationResponseScheme:
        """Редактирование быстрого меню

        Обновляет существующее быстрое меню

        :param quick_menu_update_dto: Данные для обновления быстрого меню (required)
        :type quick_menu_update_dto: QuickMenuUpdateDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_update_post_serialize(
            quick_menu_update_dto=quick_menu_update_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def v2_entities_quick_labels_update_post_with_http_info(
        self,
        quick_menu_update_dto: Annotated[QuickMenuUpdateDto, Field(description="Данные для обновления быстрого меню")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QuickMenuOperationResponseScheme]:
        """Редактирование быстрого меню

        Обновляет существующее быстрое меню

        :param quick_menu_update_dto: Данные для обновления быстрого меню (required)
        :type quick_menu_update_dto: QuickMenuUpdateDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_update_post_serialize(
            quick_menu_update_dto=quick_menu_update_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def v2_entities_quick_labels_update_post_without_preload_content(
        self,
        quick_menu_update_dto: Annotated[QuickMenuUpdateDto, Field(description="Данные для обновления быстрого меню")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Редактирование быстрого меню

        Обновляет существующее быстрое меню

        :param quick_menu_update_dto: Данные для обновления быстрого меню (required)
        :type quick_menu_update_dto: QuickMenuUpdateDto
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v2_entities_quick_labels_update_post_serialize(
            quick_menu_update_dto=quick_menu_update_dto,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QuickMenuOperationResponseScheme",
            '400': "str",
            '401': "str",
            '403': "str",
            '404': "str",
            '406': "str",
            '409': "str",
            '429': "str",
            '500': "str",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v2_entities_quick_labels_update_post_serialize(
        self,
        quick_menu_update_dto,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if quick_menu_update_dto is not None:
            _body_params = quick_menu_update_dto


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'iikoCookieAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v2/entities/quickLabels/update',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


