# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from iikoserver_client.models.budget_plan_item_value_type_enum import BudgetPlanItemValueTypeEnum
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class BudgetPlanItemDtoXml(BaseModel):
    """
    BudgetPlanItemDtoXml
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, description="Дата", alias="date")
    plan_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Плановое значение", alias="planValue")
    value_type: Optional[BudgetPlanItemValueTypeEnum] = Field(default=None, alias="valueType")
    __properties: ClassVar[List[str]] = ["date", "planValue", "valueType"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "budgetPlanItemDto",
        
        
        "field_configs": {
            "var_date": {
                "xml_name": "date",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "plan_value": {
                "xml_name": "planValue",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "value_type": {
                "xml_name": "valueType",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BudgetPlanItemDtoXml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if plan_value (nullable) is None
        # and model_fields_set contains the field
        if self.plan_value is None and "plan_value" in self.model_fields_set:
            _dict['planValue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BudgetPlanItemDtoXml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "planValue": obj.get("planValue"),
            "valueType": obj.get("valueType")
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of BudgetPlanItemDtoXml from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of BudgetPlanItemDtoXml from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: var_date (XML name: date)
        # Handle XML element: var_date
        # Single element field: var_date
        child_element = element.find("date")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["date"] = text_value
                
        
        # Process field: plan_value (XML name: planValue)
        # Handle XML element: plan_value
        # Single element field: plan_value
        child_element = element.find("planValue")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["planValue"] = float(text_value)
                except ValueError:
                    data["planValue"] = text_value
                
        
        # Process field: value_type (XML name: valueType)
        # Handle XML element: value_type
        # Single element field: value_type
        child_element = element.find("valueType")
        if child_element is not None:
            # Enum field
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["valueType"] = text_value
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: var_date (XML name: date)
        value = getattr(self, "var_date", None)
        if value is not None:  # Skip None values
            # Single element field: var_date
            child_element = SubElement(element, "date")
            child_element.text = value
            
        # Process field: plan_value (XML name: planValue)
        value = getattr(self, "plan_value", None)
        if value is not None:  # Skip None values
            # Single element field: plan_value
            child_element = SubElement(element, "planValue")
            child_element.text = str(value)
            
        # Process field: value_type (XML name: valueType)
        value = getattr(self, "value_type", None)
        if value is not None:  # Skip None values
            # Single element field: value_type
            child_element = SubElement(element, "valueType")
            # Enum field
            child_element.text = str(value)


