# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikoserver_client.models.payment_record_dto import PaymentRecordDto
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class CashShiftPaymentsDto(BaseModel):
    """
    CashShiftPaymentsDto
    """ # noqa: E501
    session_id: StrictStr = Field(description="UUID запрошенной смены", alias="sessionId")
    operation_day: Optional[date] = Field(default=None, description="Операционный день", alias="operationDay")
    cashless_records: List[PaymentRecordDto] = Field(description="Список записей, относящихся к безналичным платежам", alias="cashlessRecords")
    pay_in_records: List[PaymentRecordDto] = Field(description="Список записей, относящихся к внесениям", alias="payInRecords")
    pay_outs_records: List[PaymentRecordDto] = Field(description="Список записей, относящихся к изъятиям", alias="payOutsRecords")
    __properties: ClassVar[List[str]] = ["sessionId", "operationDay", "cashlessRecords", "payInRecords", "payOutsRecords"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "CashShiftPaymentsDto",
        
        
        "field_configs": {
            "session_id": {
                "xml_name": "sessionId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "operation_day": {
                "xml_name": "operationDay",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "cashless_records": {
                "xml_name": "cashlessRecords",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "pay_in_records": {
                "xml_name": "payInRecords",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "pay_outs_records": {
                "xml_name": "payOutsRecords",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashShiftPaymentsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cashless_records (list)
        _items = []
        if self.cashless_records:
            for _item_cashless_records in self.cashless_records:
                if _item_cashless_records:
                    _items.append(_item_cashless_records.to_dict())
            _dict['cashlessRecords'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pay_in_records (list)
        _items = []
        if self.pay_in_records:
            for _item_pay_in_records in self.pay_in_records:
                if _item_pay_in_records:
                    _items.append(_item_pay_in_records.to_dict())
            _dict['payInRecords'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pay_outs_records (list)
        _items = []
        if self.pay_outs_records:
            for _item_pay_outs_records in self.pay_outs_records:
                if _item_pay_outs_records:
                    _items.append(_item_pay_outs_records.to_dict())
            _dict['payOutsRecords'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashShiftPaymentsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessionId": obj.get("sessionId"),
            "operationDay": obj.get("operationDay"),
            "cashlessRecords": [PaymentRecordDto.from_dict(_item) for _item in obj["cashlessRecords"]] if obj.get("cashlessRecords") is not None else None,
            "payInRecords": [PaymentRecordDto.from_dict(_item) for _item in obj["payInRecords"]] if obj.get("payInRecords") is not None else None,
            "payOutsRecords": [PaymentRecordDto.from_dict(_item) for _item in obj["payOutsRecords"]] if obj.get("payOutsRecords") is not None else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of CashShiftPaymentsDto from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of CashShiftPaymentsDto from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: session_id (XML name: sessionId)
        # Handle XML element: session_id
        # Single element field: session_id
        child_element = element.find("sessionId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["sessionId"] = text_value
                
        
        # Process field: operation_day (XML name: operationDay)
        # Handle XML element: operation_day
        # Single element field: operation_day
        child_element = element.find("operationDay")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                
                # Handle other primitive types (date, datetime, uuid, etc.)
                # Date field - handle "null" specially
                if text_value == "null":
                    data["operationDay"] = None
                else:
                    data["operationDay"] = text_value
                
                
        
        # Process field: cashless_records (XML name: cashlessRecords)
        # Handle XML element: cashless_records
        # Array field: cashless_records
        # Non-wrapped array - direct elements
        # Complex items in non-wrapped array
        child_elements = element.findall("cashlessRecords")
        items = []
        for child in child_elements:
            item_obj = PaymentRecordDto.from_xml_element(child)
            if item_obj is not None:
                items.append(item_obj)
        data["cashlessRecords"] = items
        
        # Process field: pay_in_records (XML name: payInRecords)
        # Handle XML element: pay_in_records
        # Array field: pay_in_records
        # Non-wrapped array - direct elements
        # Complex items in non-wrapped array
        child_elements = element.findall("payInRecords")
        items = []
        for child in child_elements:
            item_obj = PaymentRecordDto.from_xml_element(child)
            if item_obj is not None:
                items.append(item_obj)
        data["payInRecords"] = items
        
        # Process field: pay_outs_records (XML name: payOutsRecords)
        # Handle XML element: pay_outs_records
        # Array field: pay_outs_records
        # Non-wrapped array - direct elements
        # Complex items in non-wrapped array
        child_elements = element.findall("payOutsRecords")
        items = []
        for child in child_elements:
            item_obj = PaymentRecordDto.from_xml_element(child)
            if item_obj is not None:
                items.append(item_obj)
        data["payOutsRecords"] = items
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: session_id (XML name: sessionId)
        value = getattr(self, "session_id", None)
        if value is not None:  # Skip None values
            # Single element field: session_id
            child_element = SubElement(element, "sessionId")
            child_element.text = value
            
        # Process field: operation_day (XML name: operationDay)
        value = getattr(self, "operation_day", None)
        if value is not None:  # Skip None values
            # Single element field: operation_day
            child_element = SubElement(element, "operationDay")
            
            # Handle other primitive types (date, datetime, uuid, etc.)
            child_element.text = str(value)
            
        # Process field: cashless_records (XML name: cashlessRecords)
        value = getattr(self, "cashless_records", None)
        if value is not None:  # Skip None values
            # Array field: cashless_records
            # Non-wrapped array - add elements directly
            for item in value:
                # Complex items in non-wrapped array
                if hasattr(item, "_to_xml_element_internal"):
                    item_element = SubElement(element, "cashlessRecords")
                    item._to_xml_element_internal(item_element)
        # Process field: pay_in_records (XML name: payInRecords)
        value = getattr(self, "pay_in_records", None)
        if value is not None:  # Skip None values
            # Array field: pay_in_records
            # Non-wrapped array - add elements directly
            for item in value:
                # Complex items in non-wrapped array
                if hasattr(item, "_to_xml_element_internal"):
                    item_element = SubElement(element, "payInRecords")
                    item._to_xml_element_internal(item_element)
        # Process field: pay_outs_records (XML name: payOutsRecords)
        value = getattr(self, "pay_outs_records", None)
        if value is not None:  # Skip None values
            # Array field: pay_outs_records
            # Non-wrapped array - add elements directly
            for item in value:
                # Complex items in non-wrapped array
                if hasattr(item, "_to_xml_element_internal"):
                    item_element = SubElement(element, "payOutsRecords")
                    item._to_xml_element_internal(item_element)


