# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class ChoiceBindingDto(BaseModel):
    """
    ChoiceBindingDto
    """ # noqa: E501
    modifier: Optional[StrictStr] = Field(default=None, description="UUID модификатора либо номенклатурной группы, если это групповой модификатор.")
    default_amount: Optional[StrictInt] = Field(default=None, description="Количество по умолчанию. Для группового модификатора всегда равен 0.", alias="defaultAmount")
    free_of_charge_amount: Optional[StrictInt] = Field(default=None, description="Количество бесплатных модификаторов.", alias="freeOfChargeAmount")
    minimum_amount: Optional[StrictInt] = Field(default=None, description="Минимальное количество.", alias="minimumAmount")
    maximum_amount: Optional[StrictInt] = Field(default=None, description="Максимальное количество.", alias="maximumAmount")
    hide_if_default_amount: Optional[StrictBool] = Field(default=None, description="Скрывать, если количество по умолчанию.", alias="hideIfDefaultAmount")
    required: Optional[StrictBool] = Field(default=None, description="Является ли модификатор обязательным. Начиная с версии iiko 6.2.3 данный параметр не используется.")
    child_modifiers_have_min_max_restrictions: Optional[StrictBool] = Field(default=None, description="Ограничения на мин. макс. количество у дочерних модификаторов.", alias="childModifiersHaveMinMaxRestrictions")
    splittable: Optional[StrictBool] = Field(default=None, description="Признак делимости модификатора. Используется только в схемах модификаторов.")
    child_modifiers: Optional[List[ChoiceBindingDto]] = Field(default=None, description="Дочерние модификаторы.", alias="childModifiers")
    __properties: ClassVar[List[str]] = ["modifier", "defaultAmount", "freeOfChargeAmount", "minimumAmount", "maximumAmount", "hideIfDefaultAmount", "required", "childModifiersHaveMinMaxRestrictions", "splittable", "childModifiers"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "ChoiceBindingDto",
        
        
        "field_configs": {
            "modifier": {
                "xml_name": "modifier",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "default_amount": {
                "xml_name": "defaultAmount",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "free_of_charge_amount": {
                "xml_name": "freeOfChargeAmount",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "minimum_amount": {
                "xml_name": "minimumAmount",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "maximum_amount": {
                "xml_name": "maximumAmount",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "hide_if_default_amount": {
                "xml_name": "hideIfDefaultAmount",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "required": {
                "xml_name": "required",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "child_modifiers_have_min_max_restrictions": {
                "xml_name": "childModifiersHaveMinMaxRestrictions",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "splittable": {
                "xml_name": "splittable",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "child_modifiers": {
                "xml_name": "childModifiers",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChoiceBindingDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in child_modifiers (list)
        _items = []
        if self.child_modifiers:
            for _item_child_modifiers in self.child_modifiers:
                if _item_child_modifiers:
                    _items.append(_item_child_modifiers.to_dict())
            _dict['childModifiers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChoiceBindingDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "modifier": obj.get("modifier"),
            "defaultAmount": obj.get("defaultAmount"),
            "freeOfChargeAmount": obj.get("freeOfChargeAmount"),
            "minimumAmount": obj.get("minimumAmount"),
            "maximumAmount": obj.get("maximumAmount"),
            "hideIfDefaultAmount": obj.get("hideIfDefaultAmount"),
            "required": obj.get("required"),
            "childModifiersHaveMinMaxRestrictions": obj.get("childModifiersHaveMinMaxRestrictions"),
            "splittable": obj.get("splittable"),
            "childModifiers": [ChoiceBindingDto.from_dict(_item) for _item in obj["childModifiers"]] if obj.get("childModifiers") is not None else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of ChoiceBindingDto from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of ChoiceBindingDto from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: modifier (XML name: modifier)
        # Handle XML element: modifier
        # Single element field: modifier
        child_element = element.find("modifier")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["modifier"] = text_value
                
        
        # Process field: default_amount (XML name: defaultAmount)
        # Handle XML element: default_amount
        # Single element field: default_amount
        child_element = element.find("defaultAmount")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["defaultAmount"] = int(text_value)
                except ValueError:
                    data["defaultAmount"] = text_value
                
        
        # Process field: free_of_charge_amount (XML name: freeOfChargeAmount)
        # Handle XML element: free_of_charge_amount
        # Single element field: free_of_charge_amount
        child_element = element.find("freeOfChargeAmount")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["freeOfChargeAmount"] = int(text_value)
                except ValueError:
                    data["freeOfChargeAmount"] = text_value
                
        
        # Process field: minimum_amount (XML name: minimumAmount)
        # Handle XML element: minimum_amount
        # Single element field: minimum_amount
        child_element = element.find("minimumAmount")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["minimumAmount"] = int(text_value)
                except ValueError:
                    data["minimumAmount"] = text_value
                
        
        # Process field: maximum_amount (XML name: maximumAmount)
        # Handle XML element: maximum_amount
        # Single element field: maximum_amount
        child_element = element.find("maximumAmount")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["maximumAmount"] = int(text_value)
                except ValueError:
                    data["maximumAmount"] = text_value
                
        
        # Process field: hide_if_default_amount (XML name: hideIfDefaultAmount)
        # Handle XML element: hide_if_default_amount
        # Single element field: hide_if_default_amount
        child_element = element.find("hideIfDefaultAmount")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["hideIfDefaultAmount"] = text_value.lower() == 'true'
                
        
        # Process field: required (XML name: required)
        # Handle XML element: required
        # Single element field: required
        child_element = element.find("required")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["required"] = text_value.lower() == 'true'
                
        
        # Process field: child_modifiers_have_min_max_restrictions (XML name: childModifiersHaveMinMaxRestrictions)
        # Handle XML element: child_modifiers_have_min_max_restrictions
        # Single element field: child_modifiers_have_min_max_restrictions
        child_element = element.find("childModifiersHaveMinMaxRestrictions")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["childModifiersHaveMinMaxRestrictions"] = text_value.lower() == 'true'
                
        
        # Process field: splittable (XML name: splittable)
        # Handle XML element: splittable
        # Single element field: splittable
        child_element = element.find("splittable")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["splittable"] = text_value.lower() == 'true'
                
        
        # Process field: child_modifiers (XML name: childModifiers)
        # Handle XML element: child_modifiers
        # Array field: child_modifiers
        # Non-wrapped array - direct elements
        # Complex items in non-wrapped array
        child_elements = element.findall("childModifiers")
        items = []
        for child in child_elements:
            item_obj = ChoiceBindingDto.from_xml_element(child)
            if item_obj is not None:
                items.append(item_obj)
        data["childModifiers"] = items
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: modifier (XML name: modifier)
        value = getattr(self, "modifier", None)
        if value is not None:  # Skip None values
            # Single element field: modifier
            child_element = SubElement(element, "modifier")
            child_element.text = value
            
        # Process field: default_amount (XML name: defaultAmount)
        value = getattr(self, "default_amount", None)
        if value is not None:  # Skip None values
            # Single element field: default_amount
            child_element = SubElement(element, "defaultAmount")
            child_element.text = str(value)
            
        # Process field: free_of_charge_amount (XML name: freeOfChargeAmount)
        value = getattr(self, "free_of_charge_amount", None)
        if value is not None:  # Skip None values
            # Single element field: free_of_charge_amount
            child_element = SubElement(element, "freeOfChargeAmount")
            child_element.text = str(value)
            
        # Process field: minimum_amount (XML name: minimumAmount)
        value = getattr(self, "minimum_amount", None)
        if value is not None:  # Skip None values
            # Single element field: minimum_amount
            child_element = SubElement(element, "minimumAmount")
            child_element.text = str(value)
            
        # Process field: maximum_amount (XML name: maximumAmount)
        value = getattr(self, "maximum_amount", None)
        if value is not None:  # Skip None values
            # Single element field: maximum_amount
            child_element = SubElement(element, "maximumAmount")
            child_element.text = str(value)
            
        # Process field: hide_if_default_amount (XML name: hideIfDefaultAmount)
        value = getattr(self, "hide_if_default_amount", None)
        if value is not None:  # Skip None values
            # Single element field: hide_if_default_amount
            child_element = SubElement(element, "hideIfDefaultAmount")
            child_element.text = str(value).lower()
            
        # Process field: required (XML name: required)
        value = getattr(self, "required", None)
        if value is not None:  # Skip None values
            # Single element field: required
            child_element = SubElement(element, "required")
            child_element.text = str(value).lower()
            
        # Process field: child_modifiers_have_min_max_restrictions (XML name: childModifiersHaveMinMaxRestrictions)
        value = getattr(self, "child_modifiers_have_min_max_restrictions", None)
        if value is not None:  # Skip None values
            # Single element field: child_modifiers_have_min_max_restrictions
            child_element = SubElement(element, "childModifiersHaveMinMaxRestrictions")
            child_element.text = str(value).lower()
            
        # Process field: splittable (XML name: splittable)
        value = getattr(self, "splittable", None)
        if value is not None:  # Skip None values
            # Single element field: splittable
            child_element = SubElement(element, "splittable")
            child_element.text = str(value).lower()
            
        # Process field: child_modifiers (XML name: childModifiers)
        value = getattr(self, "child_modifiers", None)
        if value is not None:  # Skip None values
            # Array field: child_modifiers
            # Non-wrapped array - add elements directly
            for item in value:
                # Complex items in non-wrapped array
                if hasattr(item, "_to_xml_element_internal"):
                    item_element = SubElement(element, "childModifiers")
                    item._to_xml_element_internal(item_element)

# TODO: Rewrite to not use raise_errors
ChoiceBindingDto.model_rebuild(raise_errors=False)

