# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class ClosedSessionDocumentItemDto(BaseModel):
    """
    ClosedSessionDocumentItemDto
    """ # noqa: E501
    num: StrictInt = Field(description="Номер элемента")
    transaction_id: StrictStr = Field(description="UUID проводки", alias="transactionId")
    sum_real: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Отредактированная сумма", alias="sumReal")
    account_override_id: Optional[StrictStr] = Field(default=None, description="Отредактированный счет", alias="accountOverrideId")
    counteragent_override_id: Optional[StrictStr] = Field(default=None, description="Отредактированный контрагент", alias="counteragentOverrideId")
    status: StrictStr = Field(description="Статус элемента")
    comment: Optional[StrictStr] = Field(default=None, description="Комментарий")
    __properties: ClassVar[List[str]] = ["num", "transactionId", "sumReal", "accountOverrideId", "counteragentOverrideId", "status", "comment"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "ClosedSessionDocumentItemDto",
        
        
        "field_configs": {
            "num": {
                "xml_name": "num",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "transaction_id": {
                "xml_name": "transactionId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "sum_real": {
                "xml_name": "sumReal",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "account_override_id": {
                "xml_name": "accountOverrideId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "counteragent_override_id": {
                "xml_name": "counteragentOverrideId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "status": {
                "xml_name": "status",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "comment": {
                "xml_name": "comment",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ACCEPTED', 'UNACCEPTED', 'HASWARNINGS']):
            raise ValueError("must be one of enum values ('ACCEPTED', 'UNACCEPTED', 'HASWARNINGS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentItemDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sum_real (nullable) is None
        # and model_fields_set contains the field
        if self.sum_real is None and "sum_real" in self.model_fields_set:
            _dict['sumReal'] = None

        # set to None if account_override_id (nullable) is None
        # and model_fields_set contains the field
        if self.account_override_id is None and "account_override_id" in self.model_fields_set:
            _dict['accountOverrideId'] = None

        # set to None if counteragent_override_id (nullable) is None
        # and model_fields_set contains the field
        if self.counteragent_override_id is None and "counteragent_override_id" in self.model_fields_set:
            _dict['counteragentOverrideId'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentItemDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "num": obj.get("num"),
            "transactionId": obj.get("transactionId"),
            "sumReal": obj.get("sumReal"),
            "accountOverrideId": obj.get("accountOverrideId"),
            "counteragentOverrideId": obj.get("counteragentOverrideId"),
            "status": obj.get("status"),
            "comment": obj.get("comment")
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentItemDto from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentItemDto from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: num (XML name: num)
        # Handle XML element: num
        # Single element field: num
        child_element = element.find("num")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["num"] = int(text_value)
                except ValueError:
                    data["num"] = text_value
                
        
        # Process field: transaction_id (XML name: transactionId)
        # Handle XML element: transaction_id
        # Single element field: transaction_id
        child_element = element.find("transactionId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["transactionId"] = text_value
                
        
        # Process field: sum_real (XML name: sumReal)
        # Handle XML element: sum_real
        # Single element field: sum_real
        child_element = element.find("sumReal")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["sumReal"] = float(text_value)
                except ValueError:
                    data["sumReal"] = text_value
                
        
        # Process field: account_override_id (XML name: accountOverrideId)
        # Handle XML element: account_override_id
        # Single element field: account_override_id
        child_element = element.find("accountOverrideId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["accountOverrideId"] = text_value
                
        
        # Process field: counteragent_override_id (XML name: counteragentOverrideId)
        # Handle XML element: counteragent_override_id
        # Single element field: counteragent_override_id
        child_element = element.find("counteragentOverrideId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["counteragentOverrideId"] = text_value
                
        
        # Process field: status (XML name: status)
        # Handle XML element: status
        # Single element field: status
        child_element = element.find("status")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["status"] = text_value
                
        
        # Process field: comment (XML name: comment)
        # Handle XML element: comment
        # Single element field: comment
        child_element = element.find("comment")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["comment"] = text_value
                
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: num (XML name: num)
        value = getattr(self, "num", None)
        if value is not None:  # Skip None values
            # Single element field: num
            child_element = SubElement(element, "num")
            child_element.text = str(value)
            
        # Process field: transaction_id (XML name: transactionId)
        value = getattr(self, "transaction_id", None)
        if value is not None:  # Skip None values
            # Single element field: transaction_id
            child_element = SubElement(element, "transactionId")
            child_element.text = value
            
        # Process field: sum_real (XML name: sumReal)
        value = getattr(self, "sum_real", None)
        if value is not None:  # Skip None values
            # Single element field: sum_real
            child_element = SubElement(element, "sumReal")
            child_element.text = str(value)
            
        # Process field: account_override_id (XML name: accountOverrideId)
        value = getattr(self, "account_override_id", None)
        if value is not None:  # Skip None values
            # Single element field: account_override_id
            child_element = SubElement(element, "accountOverrideId")
            child_element.text = value
            
        # Process field: counteragent_override_id (XML name: counteragentOverrideId)
        value = getattr(self, "counteragent_override_id", None)
        if value is not None:  # Skip None values
            # Single element field: counteragent_override_id
            child_element = SubElement(element, "counteragentOverrideId")
            child_element.text = value
            
        # Process field: status (XML name: status)
        value = getattr(self, "status", None)
        if value is not None:  # Skip None values
            # Single element field: status
            child_element = SubElement(element, "status")
            child_element.text = value
            
        # Process field: comment (XML name: comment)
        value = getattr(self, "comment", None)
        if value is not None:  # Skip None values
            # Single element field: comment
            child_element = SubElement(element, "comment")
            child_element.text = value
            


