# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikoserver_client.models.cash_shift_session_dto import CashShiftSessionDto
from iikoserver_client.models.closed_session_document_item_dto import ClosedSessionDocumentItemDto
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class ClosedSessionDocumentDto(BaseModel):
    """
    ClosedSessionDocumentDto
    """ # noqa: E501
    id: StrictStr = Field(description="Id документа")
    session: CashShiftSessionDto
    account_shortage_id: Optional[StrictStr] = Field(default=None, description="Счет, на который записывается недостача", alias="accountShortageId")
    counteragent_shortage_id: Optional[StrictStr] = Field(default=None, description="Контрагент, на которого записывается недостача", alias="counteragentShortageId")
    account_surplus_id: Optional[StrictStr] = Field(default=None, description="Счет, на который записывается излишек", alias="accountSurplusId")
    counteragent_surplus_id: Optional[StrictStr] = Field(default=None, description="Контрагент, на которого записывается излишек", alias="counteragentSurplusId")
    department_id: StrictStr = Field(description="Торговое предприятие кассовой смены", alias="departmentId")
    items: List[ClosedSessionDocumentItemDto] = Field(description="Элементы/строки документа")
    __properties: ClassVar[List[str]] = ["id", "session", "accountShortageId", "counteragentShortageId", "accountSurplusId", "counteragentSurplusId", "departmentId", "items"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "ClosedSessionDocumentDto",
        
        
        "field_configs": {
            "id": {
                "xml_name": "id",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "session": {
                "xml_name": "session",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "account_shortage_id": {
                "xml_name": "accountShortageId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "counteragent_shortage_id": {
                "xml_name": "counteragentShortageId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "account_surplus_id": {
                "xml_name": "accountSurplusId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "counteragent_surplus_id": {
                "xml_name": "counteragentSurplusId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "department_id": {
                "xml_name": "departmentId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "items": {
                "xml_name": "items",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # set to None if account_shortage_id (nullable) is None
        # and model_fields_set contains the field
        if self.account_shortage_id is None and "account_shortage_id" in self.model_fields_set:
            _dict['accountShortageId'] = None

        # set to None if counteragent_shortage_id (nullable) is None
        # and model_fields_set contains the field
        if self.counteragent_shortage_id is None and "counteragent_shortage_id" in self.model_fields_set:
            _dict['counteragentShortageId'] = None

        # set to None if account_surplus_id (nullable) is None
        # and model_fields_set contains the field
        if self.account_surplus_id is None and "account_surplus_id" in self.model_fields_set:
            _dict['accountSurplusId'] = None

        # set to None if counteragent_surplus_id (nullable) is None
        # and model_fields_set contains the field
        if self.counteragent_surplus_id is None and "counteragent_surplus_id" in self.model_fields_set:
            _dict['counteragentSurplusId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "session": CashShiftSessionDto.from_dict(obj["session"]) if obj.get("session") is not None else None,
            "accountShortageId": obj.get("accountShortageId"),
            "counteragentShortageId": obj.get("counteragentShortageId"),
            "accountSurplusId": obj.get("accountSurplusId"),
            "counteragentSurplusId": obj.get("counteragentSurplusId"),
            "departmentId": obj.get("departmentId"),
            "items": [ClosedSessionDocumentItemDto.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentDto from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of ClosedSessionDocumentDto from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: id (XML name: id)
        # Handle XML element: id
        # Single element field: id
        child_element = element.find("id")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["id"] = text_value
                
        
        # Process field: session (XML name: session)
        # Handle XML element: session
        # Single element field: session
        child_element = element.find("session")
        if child_element is not None:
            # Complex object field
            nested_obj = CashShiftSessionDto.from_xml_element(child_element)
            if nested_obj is not None:
                data["session"] = nested_obj
        
        # Process field: account_shortage_id (XML name: accountShortageId)
        # Handle XML element: account_shortage_id
        # Single element field: account_shortage_id
        child_element = element.find("accountShortageId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["accountShortageId"] = text_value
                
        
        # Process field: counteragent_shortage_id (XML name: counteragentShortageId)
        # Handle XML element: counteragent_shortage_id
        # Single element field: counteragent_shortage_id
        child_element = element.find("counteragentShortageId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["counteragentShortageId"] = text_value
                
        
        # Process field: account_surplus_id (XML name: accountSurplusId)
        # Handle XML element: account_surplus_id
        # Single element field: account_surplus_id
        child_element = element.find("accountSurplusId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["accountSurplusId"] = text_value
                
        
        # Process field: counteragent_surplus_id (XML name: counteragentSurplusId)
        # Handle XML element: counteragent_surplus_id
        # Single element field: counteragent_surplus_id
        child_element = element.find("counteragentSurplusId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["counteragentSurplusId"] = text_value
                
        
        # Process field: department_id (XML name: departmentId)
        # Handle XML element: department_id
        # Single element field: department_id
        child_element = element.find("departmentId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["departmentId"] = text_value
                
        
        # Process field: items (XML name: items)
        # Handle XML element: items
        # Array field: items
        # Non-wrapped array - direct elements
        # Complex items in non-wrapped array
        child_elements = element.findall("items")
        items = []
        for child in child_elements:
            item_obj = ClosedSessionDocumentItemDto.from_xml_element(child)
            if item_obj is not None:
                items.append(item_obj)
        data["items"] = items
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: id (XML name: id)
        value = getattr(self, "id", None)
        if value is not None:  # Skip None values
            # Single element field: id
            child_element = SubElement(element, "id")
            child_element.text = value
            
        # Process field: session (XML name: session)
        value = getattr(self, "session", None)
        if value is not None:  # Skip None values
            # Single element field: session
            child_element = SubElement(element, "session")
            # Complex object field
            if hasattr(value, "_to_xml_element_internal"):
                value._to_xml_element_internal(child_element)
        # Process field: account_shortage_id (XML name: accountShortageId)
        value = getattr(self, "account_shortage_id", None)
        if value is not None:  # Skip None values
            # Single element field: account_shortage_id
            child_element = SubElement(element, "accountShortageId")
            child_element.text = value
            
        # Process field: counteragent_shortage_id (XML name: counteragentShortageId)
        value = getattr(self, "counteragent_shortage_id", None)
        if value is not None:  # Skip None values
            # Single element field: counteragent_shortage_id
            child_element = SubElement(element, "counteragentShortageId")
            child_element.text = value
            
        # Process field: account_surplus_id (XML name: accountSurplusId)
        value = getattr(self, "account_surplus_id", None)
        if value is not None:  # Skip None values
            # Single element field: account_surplus_id
            child_element = SubElement(element, "accountSurplusId")
            child_element.text = value
            
        # Process field: counteragent_surplus_id (XML name: counteragentSurplusId)
        value = getattr(self, "counteragent_surplus_id", None)
        if value is not None:  # Skip None values
            # Single element field: counteragent_surplus_id
            child_element = SubElement(element, "counteragentSurplusId")
            child_element.text = value
            
        # Process field: department_id (XML name: departmentId)
        value = getattr(self, "department_id", None)
        if value is not None:  # Skip None values
            # Single element field: department_id
            child_element = SubElement(element, "departmentId")
            child_element.text = value
            
        # Process field: items (XML name: items)
        value = getattr(self, "items", None)
        if value is not None:  # Skip None values
            # Array field: items
            # Non-wrapped array - add elements directly
            for item in value:
                # Complex items in non-wrapped array
                if hasattr(item, "_to_xml_element_internal"):
                    item_element = SubElement(element, "items")
                    item._to_xml_element_internal(item_element)


