# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from iikoserver_client.models.metric_type_enum import MetricTypeEnum
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class DeliveryOrderCycleRowXml(BaseModel):
    """
    DeliveryOrderCycleRowXml
    """ # noqa: E501
    cutting_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Время на столе нарезки", alias="cuttingTime")
    in_restaurant_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Время в ресторане", alias="inRestaurantTime")
    on_shelf_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Время на стеллаже оперативности", alias="onShelfTime")
    on_the_way_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Время в пути", alias="onTheWayTime")
    pizza_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Время на столе Пицца", alias="pizzaTime")
    total_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Общее время", alias="totalTime")
    metric_type: Optional[MetricTypeEnum] = Field(default=None, alias="metricType")
    __properties: ClassVar[List[str]] = ["cuttingTime", "inRestaurantTime", "onShelfTime", "onTheWayTime", "pizzaTime", "totalTime", "metricType"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "row",
        
        
        "field_configs": {
            "cutting_time": {
                "xml_name": "cuttingTime",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "in_restaurant_time": {
                "xml_name": "inRestaurantTime",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "on_shelf_time": {
                "xml_name": "onShelfTime",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "on_the_way_time": {
                "xml_name": "onTheWayTime",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "pizza_time": {
                "xml_name": "pizzaTime",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "total_time": {
                "xml_name": "totalTime",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "metric_type": {
                "xml_name": "metricType",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveryOrderCycleRowXml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cutting_time (nullable) is None
        # and model_fields_set contains the field
        if self.cutting_time is None and "cutting_time" in self.model_fields_set:
            _dict['cuttingTime'] = None

        # set to None if in_restaurant_time (nullable) is None
        # and model_fields_set contains the field
        if self.in_restaurant_time is None and "in_restaurant_time" in self.model_fields_set:
            _dict['inRestaurantTime'] = None

        # set to None if on_shelf_time (nullable) is None
        # and model_fields_set contains the field
        if self.on_shelf_time is None and "on_shelf_time" in self.model_fields_set:
            _dict['onShelfTime'] = None

        # set to None if on_the_way_time (nullable) is None
        # and model_fields_set contains the field
        if self.on_the_way_time is None and "on_the_way_time" in self.model_fields_set:
            _dict['onTheWayTime'] = None

        # set to None if pizza_time (nullable) is None
        # and model_fields_set contains the field
        if self.pizza_time is None and "pizza_time" in self.model_fields_set:
            _dict['pizzaTime'] = None

        # set to None if total_time (nullable) is None
        # and model_fields_set contains the field
        if self.total_time is None and "total_time" in self.model_fields_set:
            _dict['totalTime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveryOrderCycleRowXml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cuttingTime": obj.get("cuttingTime"),
            "inRestaurantTime": obj.get("inRestaurantTime"),
            "onShelfTime": obj.get("onShelfTime"),
            "onTheWayTime": obj.get("onTheWayTime"),
            "pizzaTime": obj.get("pizzaTime"),
            "totalTime": obj.get("totalTime"),
            "metricType": obj.get("metricType")
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of DeliveryOrderCycleRowXml from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of DeliveryOrderCycleRowXml from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: cutting_time (XML name: cuttingTime)
        # Handle XML element: cutting_time
        # Single element field: cutting_time
        child_element = element.find("cuttingTime")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["cuttingTime"] = float(text_value)
                except ValueError:
                    data["cuttingTime"] = text_value
                
        
        # Process field: in_restaurant_time (XML name: inRestaurantTime)
        # Handle XML element: in_restaurant_time
        # Single element field: in_restaurant_time
        child_element = element.find("inRestaurantTime")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["inRestaurantTime"] = float(text_value)
                except ValueError:
                    data["inRestaurantTime"] = text_value
                
        
        # Process field: on_shelf_time (XML name: onShelfTime)
        # Handle XML element: on_shelf_time
        # Single element field: on_shelf_time
        child_element = element.find("onShelfTime")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["onShelfTime"] = float(text_value)
                except ValueError:
                    data["onShelfTime"] = text_value
                
        
        # Process field: on_the_way_time (XML name: onTheWayTime)
        # Handle XML element: on_the_way_time
        # Single element field: on_the_way_time
        child_element = element.find("onTheWayTime")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["onTheWayTime"] = float(text_value)
                except ValueError:
                    data["onTheWayTime"] = text_value
                
        
        # Process field: pizza_time (XML name: pizzaTime)
        # Handle XML element: pizza_time
        # Single element field: pizza_time
        child_element = element.find("pizzaTime")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["pizzaTime"] = float(text_value)
                except ValueError:
                    data["pizzaTime"] = text_value
                
        
        # Process field: total_time (XML name: totalTime)
        # Handle XML element: total_time
        # Single element field: total_time
        child_element = element.find("totalTime")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["totalTime"] = float(text_value)
                except ValueError:
                    data["totalTime"] = text_value
                
        
        # Process field: metric_type (XML name: metricType)
        # Handle XML element: metric_type
        # Single element field: metric_type
        child_element = element.find("metricType")
        if child_element is not None:
            # Enum field
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["metricType"] = text_value
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: cutting_time (XML name: cuttingTime)
        value = getattr(self, "cutting_time", None)
        if value is not None:  # Skip None values
            # Single element field: cutting_time
            child_element = SubElement(element, "cuttingTime")
            child_element.text = str(value)
            
        # Process field: in_restaurant_time (XML name: inRestaurantTime)
        value = getattr(self, "in_restaurant_time", None)
        if value is not None:  # Skip None values
            # Single element field: in_restaurant_time
            child_element = SubElement(element, "inRestaurantTime")
            child_element.text = str(value)
            
        # Process field: on_shelf_time (XML name: onShelfTime)
        value = getattr(self, "on_shelf_time", None)
        if value is not None:  # Skip None values
            # Single element field: on_shelf_time
            child_element = SubElement(element, "onShelfTime")
            child_element.text = str(value)
            
        # Process field: on_the_way_time (XML name: onTheWayTime)
        value = getattr(self, "on_the_way_time", None)
        if value is not None:  # Skip None values
            # Single element field: on_the_way_time
            child_element = SubElement(element, "onTheWayTime")
            child_element.text = str(value)
            
        # Process field: pizza_time (XML name: pizzaTime)
        value = getattr(self, "pizza_time", None)
        if value is not None:  # Skip None values
            # Single element field: pizza_time
            child_element = SubElement(element, "pizzaTime")
            child_element.text = str(value)
            
        # Process field: total_time (XML name: totalTime)
        value = getattr(self, "total_time", None)
        if value is not None:  # Skip None values
            # Single element field: total_time
            child_element = SubElement(element, "totalTime")
            child_element.text = str(value)
            
        # Process field: metric_type (XML name: metricType)
        value = getattr(self, "metric_type", None)
        if value is not None:  # Skip None values
            # Single element field: metric_type
            child_element = SubElement(element, "metricType")
            # Enum field
            child_element.text = str(value)


