# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class EmployeesByIdEmployeeUUIDPostRequest(BaseModel):
    """
    EmployeesByIdEmployeeUUIDPostRequest
    """ # noqa: E501
    code: Optional[StrictStr] = Field(default=None, description="Табельный номер сотрудника")
    name: Optional[StrictStr] = Field(default=None, description="Имя сотрудника")
    login: Optional[StrictStr] = Field(default=None, description="Логин для входа в бекофис")
    password: Optional[StrictStr] = Field(default=None, description="Пароль для входа в бекофис")
    main_role_code: Optional[StrictStr] = Field(default=None, description="Код основной должности", alias="mainRoleCode")
    role_codes: Optional[List[StrictStr]] = Field(default=None, description="Коды должностей", alias="roleCodes")
    phone: Optional[StrictStr] = Field(default=None, description="Телефон")
    cell_phone: Optional[StrictStr] = Field(default=None, description="Мобильный телефон", alias="cellPhone")
    first_name: Optional[StrictStr] = Field(default=None, description="Имя", alias="firstName")
    middle_name: Optional[StrictStr] = Field(default=None, description="Отчество", alias="middleName")
    last_name: Optional[StrictStr] = Field(default=None, description="Фамилия", alias="lastName")
    birthday: Optional[datetime] = Field(default=None, description="Дата рождения")
    email: Optional[StrictStr] = Field(default=None, description="Email")
    address: Optional[StrictStr] = Field(default=None, description="Адрес")
    hire_date: Optional[StrictStr] = Field(default=None, description="Дата найма", alias="hireDate")
    fire_date: Optional[date] = Field(default=None, description="Дата увольнения", alias="fireDate")
    note: Optional[StrictStr] = Field(default=None, description="Примечание")
    card_number: Optional[StrictStr] = Field(default=None, description="Slip карты сотрудника", alias="cardNumber")
    pin_code: Optional[StrictStr] = Field(default=None, description="Pin-код для входа в iikoFront", alias="pinCode")
    taxpayer_id_number: Optional[StrictStr] = Field(default=None, description="ИНН", alias="taxpayerIdNumber")
    snils: Optional[StrictStr] = Field(default=None, description="СНИЛС")
    gln: Optional[StrictStr] = Field(default=None, description="Global Location Number для поставщиков")
    preferred_department_code: Optional[StrictStr] = Field(default=None, description="Код предпочитаемого подразделения", alias="preferredDepartmentCode")
    department_codes: Optional[List[StrictStr]] = Field(default=None, description="Коды назначенных подразделений", alias="departmentCodes")
    responsibility_department_codes: Optional[List[StrictStr]] = Field(default=None, description="Коды подразделений, где сотрудник является ответственным", alias="responsibilityDepartmentCodes")
    deleted: Optional[StrictBool] = Field(default=None, description="Признак удаления")
    supplier: Optional[StrictBool] = Field(default=None, description="Признак поставщика")
    employee: Optional[StrictBool] = Field(default=None, description="Признак сотрудника")
    client: Optional[StrictBool] = Field(default=None, description="Признак клиента")
    external_data: Optional[StrictStr] = Field(default=None, description="Произвольные данные в XML формате", alias="externalData")
    __properties: ClassVar[List[str]] = ["code", "name", "login", "password", "mainRoleCode", "roleCodes", "phone", "cellPhone", "firstName", "middleName", "lastName", "birthday", "email", "address", "hireDate", "fireDate", "note", "cardNumber", "pinCode", "taxpayerIdNumber", "snils", "gln", "preferredDepartmentCode", "departmentCodes", "responsibilityDepartmentCodes", "deleted", "supplier", "employee", "client", "externalData"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "EmployeesByIdEmployeeUUIDPostRequest",
        
        
        "field_configs": {
            "code": {
                "xml_name": "code",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "name": {
                "xml_name": "name",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "login": {
                "xml_name": "login",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "password": {
                "xml_name": "password",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "main_role_code": {
                "xml_name": "mainRoleCode",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "role_codes": {
                "xml_name": "roleCodes",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "phone": {
                "xml_name": "phone",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "cell_phone": {
                "xml_name": "cellPhone",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "first_name": {
                "xml_name": "firstName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "middle_name": {
                "xml_name": "middleName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "last_name": {
                "xml_name": "lastName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "birthday": {
                "xml_name": "birthday",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "email": {
                "xml_name": "email",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "address": {
                "xml_name": "address",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "hire_date": {
                "xml_name": "hireDate",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "fire_date": {
                "xml_name": "fireDate",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "note": {
                "xml_name": "note",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "card_number": {
                "xml_name": "cardNumber",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "pin_code": {
                "xml_name": "pinCode",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "taxpayer_id_number": {
                "xml_name": "taxpayerIdNumber",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "snils": {
                "xml_name": "snils",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "gln": {
                "xml_name": "gln",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "preferred_department_code": {
                "xml_name": "preferredDepartmentCode",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "department_codes": {
                "xml_name": "departmentCodes",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "responsibility_department_codes": {
                "xml_name": "responsibilityDepartmentCodes",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "deleted": {
                "xml_name": "deleted",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "supplier": {
                "xml_name": "supplier",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "employee": {
                "xml_name": "employee",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "client": {
                "xml_name": "client",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "external_data": {
                "xml_name": "externalData",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmployeesByIdEmployeeUUIDPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmployeesByIdEmployeeUUIDPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "name": obj.get("name"),
            "login": obj.get("login"),
            "password": obj.get("password"),
            "mainRoleCode": obj.get("mainRoleCode"),
            "roleCodes": obj.get("roleCodes"),
            "phone": obj.get("phone"),
            "cellPhone": obj.get("cellPhone"),
            "firstName": obj.get("firstName"),
            "middleName": obj.get("middleName"),
            "lastName": obj.get("lastName"),
            "birthday": obj.get("birthday"),
            "email": obj.get("email"),
            "address": obj.get("address"),
            "hireDate": obj.get("hireDate"),
            "fireDate": obj.get("fireDate"),
            "note": obj.get("note"),
            "cardNumber": obj.get("cardNumber"),
            "pinCode": obj.get("pinCode"),
            "taxpayerIdNumber": obj.get("taxpayerIdNumber"),
            "snils": obj.get("snils"),
            "gln": obj.get("gln"),
            "preferredDepartmentCode": obj.get("preferredDepartmentCode"),
            "departmentCodes": obj.get("departmentCodes"),
            "responsibilityDepartmentCodes": obj.get("responsibilityDepartmentCodes"),
            "deleted": obj.get("deleted"),
            "supplier": obj.get("supplier"),
            "employee": obj.get("employee"),
            "client": obj.get("client"),
            "externalData": obj.get("externalData")
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of EmployeesByIdEmployeeUUIDPostRequest from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of EmployeesByIdEmployeeUUIDPostRequest from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: code (XML name: code)
        # Handle XML element: code
        # Single element field: code
        child_element = element.find("code")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["code"] = text_value
                
        
        # Process field: name (XML name: name)
        # Handle XML element: name
        # Single element field: name
        child_element = element.find("name")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["name"] = text_value
                
        
        # Process field: login (XML name: login)
        # Handle XML element: login
        # Single element field: login
        child_element = element.find("login")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["login"] = text_value
                
        
        # Process field: password (XML name: password)
        # Handle XML element: password
        # Single element field: password
        child_element = element.find("password")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["password"] = text_value
                
        
        # Process field: main_role_code (XML name: mainRoleCode)
        # Handle XML element: main_role_code
        # Single element field: main_role_code
        child_element = element.find("mainRoleCode")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["mainRoleCode"] = text_value
                
        
        # Process field: role_codes (XML name: roleCodes)
        # Handle XML element: role_codes
        # Array field: role_codes
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("roleCodes")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["roleCodes"] = items
        
        # Process field: phone (XML name: phone)
        # Handle XML element: phone
        # Single element field: phone
        child_element = element.find("phone")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["phone"] = text_value
                
        
        # Process field: cell_phone (XML name: cellPhone)
        # Handle XML element: cell_phone
        # Single element field: cell_phone
        child_element = element.find("cellPhone")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["cellPhone"] = text_value
                
        
        # Process field: first_name (XML name: firstName)
        # Handle XML element: first_name
        # Single element field: first_name
        child_element = element.find("firstName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["firstName"] = text_value
                
        
        # Process field: middle_name (XML name: middleName)
        # Handle XML element: middle_name
        # Single element field: middle_name
        child_element = element.find("middleName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["middleName"] = text_value
                
        
        # Process field: last_name (XML name: lastName)
        # Handle XML element: last_name
        # Single element field: last_name
        child_element = element.find("lastName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["lastName"] = text_value
                
        
        # Process field: birthday (XML name: birthday)
        # Handle XML element: birthday
        # Single element field: birthday
        child_element = element.find("birthday")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                
                # Handle other primitive types (date, datetime, uuid, etc.)
                # DateTime field - handle "null" specially  
                if text_value == "null":
                    data["birthday"] = None
                else:
                    data["birthday"] = text_value
                
                
        
        # Process field: email (XML name: email)
        # Handle XML element: email
        # Single element field: email
        child_element = element.find("email")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["email"] = text_value
                
        
        # Process field: address (XML name: address)
        # Handle XML element: address
        # Single element field: address
        child_element = element.find("address")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["address"] = text_value
                
        
        # Process field: hire_date (XML name: hireDate)
        # Handle XML element: hire_date
        # Single element field: hire_date
        child_element = element.find("hireDate")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["hireDate"] = text_value
                
        
        # Process field: fire_date (XML name: fireDate)
        # Handle XML element: fire_date
        # Single element field: fire_date
        child_element = element.find("fireDate")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                
                # Handle other primitive types (date, datetime, uuid, etc.)
                # Date field - handle "null" specially
                if text_value == "null":
                    data["fireDate"] = None
                else:
                    data["fireDate"] = text_value
                
                
        
        # Process field: note (XML name: note)
        # Handle XML element: note
        # Single element field: note
        child_element = element.find("note")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["note"] = text_value
                
        
        # Process field: card_number (XML name: cardNumber)
        # Handle XML element: card_number
        # Single element field: card_number
        child_element = element.find("cardNumber")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["cardNumber"] = text_value
                
        
        # Process field: pin_code (XML name: pinCode)
        # Handle XML element: pin_code
        # Single element field: pin_code
        child_element = element.find("pinCode")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["pinCode"] = text_value
                
        
        # Process field: taxpayer_id_number (XML name: taxpayerIdNumber)
        # Handle XML element: taxpayer_id_number
        # Single element field: taxpayer_id_number
        child_element = element.find("taxpayerIdNumber")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["taxpayerIdNumber"] = text_value
                
        
        # Process field: snils (XML name: snils)
        # Handle XML element: snils
        # Single element field: snils
        child_element = element.find("snils")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["snils"] = text_value
                
        
        # Process field: gln (XML name: gln)
        # Handle XML element: gln
        # Single element field: gln
        child_element = element.find("gln")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["gln"] = text_value
                
        
        # Process field: preferred_department_code (XML name: preferredDepartmentCode)
        # Handle XML element: preferred_department_code
        # Single element field: preferred_department_code
        child_element = element.find("preferredDepartmentCode")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["preferredDepartmentCode"] = text_value
                
        
        # Process field: department_codes (XML name: departmentCodes)
        # Handle XML element: department_codes
        # Array field: department_codes
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("departmentCodes")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["departmentCodes"] = items
        
        # Process field: responsibility_department_codes (XML name: responsibilityDepartmentCodes)
        # Handle XML element: responsibility_department_codes
        # Array field: responsibility_department_codes
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("responsibilityDepartmentCodes")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["responsibilityDepartmentCodes"] = items
        
        # Process field: deleted (XML name: deleted)
        # Handle XML element: deleted
        # Single element field: deleted
        child_element = element.find("deleted")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["deleted"] = text_value.lower() == 'true'
                
        
        # Process field: supplier (XML name: supplier)
        # Handle XML element: supplier
        # Single element field: supplier
        child_element = element.find("supplier")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["supplier"] = text_value.lower() == 'true'
                
        
        # Process field: employee (XML name: employee)
        # Handle XML element: employee
        # Single element field: employee
        child_element = element.find("employee")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["employee"] = text_value.lower() == 'true'
                
        
        # Process field: client (XML name: client)
        # Handle XML element: client
        # Single element field: client
        child_element = element.find("client")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["client"] = text_value.lower() == 'true'
                
        
        # Process field: external_data (XML name: externalData)
        # Handle XML element: external_data
        # Single element field: external_data
        child_element = element.find("externalData")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["externalData"] = text_value
                
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: code (XML name: code)
        value = getattr(self, "code", None)
        if value is not None:  # Skip None values
            # Single element field: code
            child_element = SubElement(element, "code")
            child_element.text = value
            
        # Process field: name (XML name: name)
        value = getattr(self, "name", None)
        if value is not None:  # Skip None values
            # Single element field: name
            child_element = SubElement(element, "name")
            child_element.text = value
            
        # Process field: login (XML name: login)
        value = getattr(self, "login", None)
        if value is not None:  # Skip None values
            # Single element field: login
            child_element = SubElement(element, "login")
            child_element.text = value
            
        # Process field: password (XML name: password)
        value = getattr(self, "password", None)
        if value is not None:  # Skip None values
            # Single element field: password
            child_element = SubElement(element, "password")
            child_element.text = value
            
        # Process field: main_role_code (XML name: mainRoleCode)
        value = getattr(self, "main_role_code", None)
        if value is not None:  # Skip None values
            # Single element field: main_role_code
            child_element = SubElement(element, "mainRoleCode")
            child_element.text = value
            
        # Process field: role_codes (XML name: roleCodes)
        value = getattr(self, "role_codes", None)
        if value is not None:  # Skip None values
            # Array field: role_codes
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "roleCodes")
                item_element.text = item
                
        # Process field: phone (XML name: phone)
        value = getattr(self, "phone", None)
        if value is not None:  # Skip None values
            # Single element field: phone
            child_element = SubElement(element, "phone")
            child_element.text = value
            
        # Process field: cell_phone (XML name: cellPhone)
        value = getattr(self, "cell_phone", None)
        if value is not None:  # Skip None values
            # Single element field: cell_phone
            child_element = SubElement(element, "cellPhone")
            child_element.text = value
            
        # Process field: first_name (XML name: firstName)
        value = getattr(self, "first_name", None)
        if value is not None:  # Skip None values
            # Single element field: first_name
            child_element = SubElement(element, "firstName")
            child_element.text = value
            
        # Process field: middle_name (XML name: middleName)
        value = getattr(self, "middle_name", None)
        if value is not None:  # Skip None values
            # Single element field: middle_name
            child_element = SubElement(element, "middleName")
            child_element.text = value
            
        # Process field: last_name (XML name: lastName)
        value = getattr(self, "last_name", None)
        if value is not None:  # Skip None values
            # Single element field: last_name
            child_element = SubElement(element, "lastName")
            child_element.text = value
            
        # Process field: birthday (XML name: birthday)
        value = getattr(self, "birthday", None)
        if value is not None:  # Skip None values
            # Single element field: birthday
            child_element = SubElement(element, "birthday")
            
            # Handle other primitive types (date, datetime, uuid, etc.)
            child_element.text = str(value)
            
        # Process field: email (XML name: email)
        value = getattr(self, "email", None)
        if value is not None:  # Skip None values
            # Single element field: email
            child_element = SubElement(element, "email")
            child_element.text = value
            
        # Process field: address (XML name: address)
        value = getattr(self, "address", None)
        if value is not None:  # Skip None values
            # Single element field: address
            child_element = SubElement(element, "address")
            child_element.text = value
            
        # Process field: hire_date (XML name: hireDate)
        value = getattr(self, "hire_date", None)
        if value is not None:  # Skip None values
            # Single element field: hire_date
            child_element = SubElement(element, "hireDate")
            child_element.text = value
            
        # Process field: fire_date (XML name: fireDate)
        value = getattr(self, "fire_date", None)
        if value is not None:  # Skip None values
            # Single element field: fire_date
            child_element = SubElement(element, "fireDate")
            
            # Handle other primitive types (date, datetime, uuid, etc.)
            child_element.text = str(value)
            
        # Process field: note (XML name: note)
        value = getattr(self, "note", None)
        if value is not None:  # Skip None values
            # Single element field: note
            child_element = SubElement(element, "note")
            child_element.text = value
            
        # Process field: card_number (XML name: cardNumber)
        value = getattr(self, "card_number", None)
        if value is not None:  # Skip None values
            # Single element field: card_number
            child_element = SubElement(element, "cardNumber")
            child_element.text = value
            
        # Process field: pin_code (XML name: pinCode)
        value = getattr(self, "pin_code", None)
        if value is not None:  # Skip None values
            # Single element field: pin_code
            child_element = SubElement(element, "pinCode")
            child_element.text = value
            
        # Process field: taxpayer_id_number (XML name: taxpayerIdNumber)
        value = getattr(self, "taxpayer_id_number", None)
        if value is not None:  # Skip None values
            # Single element field: taxpayer_id_number
            child_element = SubElement(element, "taxpayerIdNumber")
            child_element.text = value
            
        # Process field: snils (XML name: snils)
        value = getattr(self, "snils", None)
        if value is not None:  # Skip None values
            # Single element field: snils
            child_element = SubElement(element, "snils")
            child_element.text = value
            
        # Process field: gln (XML name: gln)
        value = getattr(self, "gln", None)
        if value is not None:  # Skip None values
            # Single element field: gln
            child_element = SubElement(element, "gln")
            child_element.text = value
            
        # Process field: preferred_department_code (XML name: preferredDepartmentCode)
        value = getattr(self, "preferred_department_code", None)
        if value is not None:  # Skip None values
            # Single element field: preferred_department_code
            child_element = SubElement(element, "preferredDepartmentCode")
            child_element.text = value
            
        # Process field: department_codes (XML name: departmentCodes)
        value = getattr(self, "department_codes", None)
        if value is not None:  # Skip None values
            # Array field: department_codes
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "departmentCodes")
                item_element.text = item
                
        # Process field: responsibility_department_codes (XML name: responsibilityDepartmentCodes)
        value = getattr(self, "responsibility_department_codes", None)
        if value is not None:  # Skip None values
            # Array field: responsibility_department_codes
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "responsibilityDepartmentCodes")
                item_element.text = item
                
        # Process field: deleted (XML name: deleted)
        value = getattr(self, "deleted", None)
        if value is not None:  # Skip None values
            # Single element field: deleted
            child_element = SubElement(element, "deleted")
            child_element.text = str(value).lower()
            
        # Process field: supplier (XML name: supplier)
        value = getattr(self, "supplier", None)
        if value is not None:  # Skip None values
            # Single element field: supplier
            child_element = SubElement(element, "supplier")
            child_element.text = str(value).lower()
            
        # Process field: employee (XML name: employee)
        value = getattr(self, "employee", None)
        if value is not None:  # Skip None values
            # Single element field: employee
            child_element = SubElement(element, "employee")
            child_element.text = str(value).lower()
            
        # Process field: client (XML name: client)
        value = getattr(self, "client", None)
        if value is not None:  # Skip None values
            # Single element field: client
            child_element = SubElement(element, "client")
            child_element.text = str(value).lower()
            
        # Process field: external_data (XML name: externalData)
        value = getattr(self, "external_data", None)
        if value is not None:  # Skip None values
            # Single element field: external_data
            child_element = SubElement(element, "externalData")
            child_element.text = value
            


