# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class IngredientEntryDtoXml(BaseModel):
    """
    IngredientEntryDtoXml
    """ # noqa: E501
    amount_in_main_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Брутто в основной единице измерения (кг)", alias="amountInMainUnit")
    amount_in_measure_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Брутто в единицах измерения продукта", alias="amountInMeasureUnit")
    amount_middle_main_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Нетто в основной единице измерения (кг)", alias="amountMiddleMainUnit")
    amount_middle_measure_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Нетто в единицах измерения продукта", alias="amountMiddleMeasureUnit")
    amount_out_main_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Выход в основной единице измерения (кг)", alias="amountOutMainUnit")
    amount_out_measure_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Выход в единицах измерения продукта", alias="amountOutMeasureUnit")
    cold_loss: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Потери при холодной обработке (%)", alias="coldLoss")
    cost_norm: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Процент себестоимости, т.е процент который составляет стоимость ингредиентов от стоимости блюда", alias="costNorm")
    dish_cost_norm: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Себестоимость блюда", alias="dishCostNorm")
    dish_sale_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Цена продажи блюда", alias="dishSalePrice")
    hot_loss: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Потери при горячей обработке (%)", alias="hotLoss")
    item_id: Optional[StrictStr] = Field(default=None, description="ИД строки отчета для представления в виде дерева (guid)", alias="itemId")
    item_parent_id: Optional[StrictStr] = Field(default=None, description="ИД родительской строки отчета для представления в виде дерева (guid)", alias="itemParentId")
    name: Optional[StrictStr] = Field(default=None, description="Наименование продукта")
    num: Optional[StrictStr] = Field(default=None, description="Артикул продукта")
    product: Optional[StrictStr] = Field(default=None, description="ИД продукта (guid)")
    product_in_dish_cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Стоимость товара в блюде", alias="productInDishCost")
    source_product_cost_norm: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Себестоимость продукта, по которому строится отчет", alias="sourceProductCostNorm")
    tree_level: StrictInt = Field(description="Уровень строки в дереве", alias="treeLevel")
    unit: Optional[StrictStr] = Field(default=None, description="Наименование единицы измерения")
    __properties: ClassVar[List[str]] = ["amountInMainUnit", "amountInMeasureUnit", "amountMiddleMainUnit", "amountMiddleMeasureUnit", "amountOutMainUnit", "amountOutMeasureUnit", "coldLoss", "costNorm", "dishCostNorm", "dishSalePrice", "hotLoss", "itemId", "itemParentId", "name", "num", "product", "productInDishCost", "sourceProductCostNorm", "treeLevel", "unit"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "ingredientEntryDto",
        
        
        "field_configs": {
            "amount_in_main_unit": {
                "xml_name": "amountInMainUnit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "amount_in_measure_unit": {
                "xml_name": "amountInMeasureUnit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "amount_middle_main_unit": {
                "xml_name": "amountMiddleMainUnit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "amount_middle_measure_unit": {
                "xml_name": "amountMiddleMeasureUnit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "amount_out_main_unit": {
                "xml_name": "amountOutMainUnit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "amount_out_measure_unit": {
                "xml_name": "amountOutMeasureUnit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "cold_loss": {
                "xml_name": "coldLoss",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "cost_norm": {
                "xml_name": "costNorm",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "dish_cost_norm": {
                "xml_name": "dishCostNorm",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "dish_sale_price": {
                "xml_name": "dishSalePrice",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "hot_loss": {
                "xml_name": "hotLoss",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "item_id": {
                "xml_name": "itemId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "item_parent_id": {
                "xml_name": "itemParentId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "name": {
                "xml_name": "name",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "num": {
                "xml_name": "num",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "product": {
                "xml_name": "product",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "product_in_dish_cost": {
                "xml_name": "productInDishCost",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "source_product_cost_norm": {
                "xml_name": "sourceProductCostNorm",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "tree_level": {
                "xml_name": "treeLevel",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "unit": {
                "xml_name": "unit",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IngredientEntryDtoXml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if amount_in_main_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_in_main_unit is None and "amount_in_main_unit" in self.model_fields_set:
            _dict['amountInMainUnit'] = None

        # set to None if amount_in_measure_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_in_measure_unit is None and "amount_in_measure_unit" in self.model_fields_set:
            _dict['amountInMeasureUnit'] = None

        # set to None if amount_middle_main_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_middle_main_unit is None and "amount_middle_main_unit" in self.model_fields_set:
            _dict['amountMiddleMainUnit'] = None

        # set to None if amount_middle_measure_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_middle_measure_unit is None and "amount_middle_measure_unit" in self.model_fields_set:
            _dict['amountMiddleMeasureUnit'] = None

        # set to None if amount_out_main_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_out_main_unit is None and "amount_out_main_unit" in self.model_fields_set:
            _dict['amountOutMainUnit'] = None

        # set to None if amount_out_measure_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_out_measure_unit is None and "amount_out_measure_unit" in self.model_fields_set:
            _dict['amountOutMeasureUnit'] = None

        # set to None if cold_loss (nullable) is None
        # and model_fields_set contains the field
        if self.cold_loss is None and "cold_loss" in self.model_fields_set:
            _dict['coldLoss'] = None

        # set to None if cost_norm (nullable) is None
        # and model_fields_set contains the field
        if self.cost_norm is None and "cost_norm" in self.model_fields_set:
            _dict['costNorm'] = None

        # set to None if dish_cost_norm (nullable) is None
        # and model_fields_set contains the field
        if self.dish_cost_norm is None and "dish_cost_norm" in self.model_fields_set:
            _dict['dishCostNorm'] = None

        # set to None if dish_sale_price (nullable) is None
        # and model_fields_set contains the field
        if self.dish_sale_price is None and "dish_sale_price" in self.model_fields_set:
            _dict['dishSalePrice'] = None

        # set to None if hot_loss (nullable) is None
        # and model_fields_set contains the field
        if self.hot_loss is None and "hot_loss" in self.model_fields_set:
            _dict['hotLoss'] = None

        # set to None if item_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_id is None and "item_id" in self.model_fields_set:
            _dict['itemId'] = None

        # set to None if item_parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_parent_id is None and "item_parent_id" in self.model_fields_set:
            _dict['itemParentId'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if num (nullable) is None
        # and model_fields_set contains the field
        if self.num is None and "num" in self.model_fields_set:
            _dict['num'] = None

        # set to None if product (nullable) is None
        # and model_fields_set contains the field
        if self.product is None and "product" in self.model_fields_set:
            _dict['product'] = None

        # set to None if product_in_dish_cost (nullable) is None
        # and model_fields_set contains the field
        if self.product_in_dish_cost is None and "product_in_dish_cost" in self.model_fields_set:
            _dict['productInDishCost'] = None

        # set to None if source_product_cost_norm (nullable) is None
        # and model_fields_set contains the field
        if self.source_product_cost_norm is None and "source_product_cost_norm" in self.model_fields_set:
            _dict['sourceProductCostNorm'] = None

        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IngredientEntryDtoXml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amountInMainUnit": obj.get("amountInMainUnit"),
            "amountInMeasureUnit": obj.get("amountInMeasureUnit"),
            "amountMiddleMainUnit": obj.get("amountMiddleMainUnit"),
            "amountMiddleMeasureUnit": obj.get("amountMiddleMeasureUnit"),
            "amountOutMainUnit": obj.get("amountOutMainUnit"),
            "amountOutMeasureUnit": obj.get("amountOutMeasureUnit"),
            "coldLoss": obj.get("coldLoss"),
            "costNorm": obj.get("costNorm"),
            "dishCostNorm": obj.get("dishCostNorm"),
            "dishSalePrice": obj.get("dishSalePrice"),
            "hotLoss": obj.get("hotLoss"),
            "itemId": obj.get("itemId"),
            "itemParentId": obj.get("itemParentId"),
            "name": obj.get("name"),
            "num": obj.get("num"),
            "product": obj.get("product"),
            "productInDishCost": obj.get("productInDishCost"),
            "sourceProductCostNorm": obj.get("sourceProductCostNorm"),
            "treeLevel": obj.get("treeLevel"),
            "unit": obj.get("unit")
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of IngredientEntryDtoXml from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of IngredientEntryDtoXml from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: amount_in_main_unit (XML name: amountInMainUnit)
        # Handle XML element: amount_in_main_unit
        # Single element field: amount_in_main_unit
        child_element = element.find("amountInMainUnit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["amountInMainUnit"] = float(text_value)
                except ValueError:
                    data["amountInMainUnit"] = text_value
                
        
        # Process field: amount_in_measure_unit (XML name: amountInMeasureUnit)
        # Handle XML element: amount_in_measure_unit
        # Single element field: amount_in_measure_unit
        child_element = element.find("amountInMeasureUnit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["amountInMeasureUnit"] = float(text_value)
                except ValueError:
                    data["amountInMeasureUnit"] = text_value
                
        
        # Process field: amount_middle_main_unit (XML name: amountMiddleMainUnit)
        # Handle XML element: amount_middle_main_unit
        # Single element field: amount_middle_main_unit
        child_element = element.find("amountMiddleMainUnit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["amountMiddleMainUnit"] = float(text_value)
                except ValueError:
                    data["amountMiddleMainUnit"] = text_value
                
        
        # Process field: amount_middle_measure_unit (XML name: amountMiddleMeasureUnit)
        # Handle XML element: amount_middle_measure_unit
        # Single element field: amount_middle_measure_unit
        child_element = element.find("amountMiddleMeasureUnit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["amountMiddleMeasureUnit"] = float(text_value)
                except ValueError:
                    data["amountMiddleMeasureUnit"] = text_value
                
        
        # Process field: amount_out_main_unit (XML name: amountOutMainUnit)
        # Handle XML element: amount_out_main_unit
        # Single element field: amount_out_main_unit
        child_element = element.find("amountOutMainUnit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["amountOutMainUnit"] = float(text_value)
                except ValueError:
                    data["amountOutMainUnit"] = text_value
                
        
        # Process field: amount_out_measure_unit (XML name: amountOutMeasureUnit)
        # Handle XML element: amount_out_measure_unit
        # Single element field: amount_out_measure_unit
        child_element = element.find("amountOutMeasureUnit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["amountOutMeasureUnit"] = float(text_value)
                except ValueError:
                    data["amountOutMeasureUnit"] = text_value
                
        
        # Process field: cold_loss (XML name: coldLoss)
        # Handle XML element: cold_loss
        # Single element field: cold_loss
        child_element = element.find("coldLoss")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["coldLoss"] = float(text_value)
                except ValueError:
                    data["coldLoss"] = text_value
                
        
        # Process field: cost_norm (XML name: costNorm)
        # Handle XML element: cost_norm
        # Single element field: cost_norm
        child_element = element.find("costNorm")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["costNorm"] = float(text_value)
                except ValueError:
                    data["costNorm"] = text_value
                
        
        # Process field: dish_cost_norm (XML name: dishCostNorm)
        # Handle XML element: dish_cost_norm
        # Single element field: dish_cost_norm
        child_element = element.find("dishCostNorm")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["dishCostNorm"] = float(text_value)
                except ValueError:
                    data["dishCostNorm"] = text_value
                
        
        # Process field: dish_sale_price (XML name: dishSalePrice)
        # Handle XML element: dish_sale_price
        # Single element field: dish_sale_price
        child_element = element.find("dishSalePrice")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["dishSalePrice"] = float(text_value)
                except ValueError:
                    data["dishSalePrice"] = text_value
                
        
        # Process field: hot_loss (XML name: hotLoss)
        # Handle XML element: hot_loss
        # Single element field: hot_loss
        child_element = element.find("hotLoss")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["hotLoss"] = float(text_value)
                except ValueError:
                    data["hotLoss"] = text_value
                
        
        # Process field: item_id (XML name: itemId)
        # Handle XML element: item_id
        # Single element field: item_id
        child_element = element.find("itemId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["itemId"] = text_value
                
        
        # Process field: item_parent_id (XML name: itemParentId)
        # Handle XML element: item_parent_id
        # Single element field: item_parent_id
        child_element = element.find("itemParentId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["itemParentId"] = text_value
                
        
        # Process field: name (XML name: name)
        # Handle XML element: name
        # Single element field: name
        child_element = element.find("name")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["name"] = text_value
                
        
        # Process field: num (XML name: num)
        # Handle XML element: num
        # Single element field: num
        child_element = element.find("num")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["num"] = text_value
                
        
        # Process field: product (XML name: product)
        # Handle XML element: product
        # Single element field: product
        child_element = element.find("product")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["product"] = text_value
                
        
        # Process field: product_in_dish_cost (XML name: productInDishCost)
        # Handle XML element: product_in_dish_cost
        # Single element field: product_in_dish_cost
        child_element = element.find("productInDishCost")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["productInDishCost"] = float(text_value)
                except ValueError:
                    data["productInDishCost"] = text_value
                
        
        # Process field: source_product_cost_norm (XML name: sourceProductCostNorm)
        # Handle XML element: source_product_cost_norm
        # Single element field: source_product_cost_norm
        child_element = element.find("sourceProductCostNorm")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["sourceProductCostNorm"] = float(text_value)
                except ValueError:
                    data["sourceProductCostNorm"] = text_value
                
        
        # Process field: tree_level (XML name: treeLevel)
        # Handle XML element: tree_level
        # Single element field: tree_level
        child_element = element.find("treeLevel")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["treeLevel"] = int(text_value)
                except ValueError:
                    data["treeLevel"] = text_value
                
        
        # Process field: unit (XML name: unit)
        # Handle XML element: unit
        # Single element field: unit
        child_element = element.find("unit")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["unit"] = text_value
                
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: amount_in_main_unit (XML name: amountInMainUnit)
        value = getattr(self, "amount_in_main_unit", None)
        if value is not None:  # Skip None values
            # Single element field: amount_in_main_unit
            child_element = SubElement(element, "amountInMainUnit")
            child_element.text = str(value)
            
        # Process field: amount_in_measure_unit (XML name: amountInMeasureUnit)
        value = getattr(self, "amount_in_measure_unit", None)
        if value is not None:  # Skip None values
            # Single element field: amount_in_measure_unit
            child_element = SubElement(element, "amountInMeasureUnit")
            child_element.text = str(value)
            
        # Process field: amount_middle_main_unit (XML name: amountMiddleMainUnit)
        value = getattr(self, "amount_middle_main_unit", None)
        if value is not None:  # Skip None values
            # Single element field: amount_middle_main_unit
            child_element = SubElement(element, "amountMiddleMainUnit")
            child_element.text = str(value)
            
        # Process field: amount_middle_measure_unit (XML name: amountMiddleMeasureUnit)
        value = getattr(self, "amount_middle_measure_unit", None)
        if value is not None:  # Skip None values
            # Single element field: amount_middle_measure_unit
            child_element = SubElement(element, "amountMiddleMeasureUnit")
            child_element.text = str(value)
            
        # Process field: amount_out_main_unit (XML name: amountOutMainUnit)
        value = getattr(self, "amount_out_main_unit", None)
        if value is not None:  # Skip None values
            # Single element field: amount_out_main_unit
            child_element = SubElement(element, "amountOutMainUnit")
            child_element.text = str(value)
            
        # Process field: amount_out_measure_unit (XML name: amountOutMeasureUnit)
        value = getattr(self, "amount_out_measure_unit", None)
        if value is not None:  # Skip None values
            # Single element field: amount_out_measure_unit
            child_element = SubElement(element, "amountOutMeasureUnit")
            child_element.text = str(value)
            
        # Process field: cold_loss (XML name: coldLoss)
        value = getattr(self, "cold_loss", None)
        if value is not None:  # Skip None values
            # Single element field: cold_loss
            child_element = SubElement(element, "coldLoss")
            child_element.text = str(value)
            
        # Process field: cost_norm (XML name: costNorm)
        value = getattr(self, "cost_norm", None)
        if value is not None:  # Skip None values
            # Single element field: cost_norm
            child_element = SubElement(element, "costNorm")
            child_element.text = str(value)
            
        # Process field: dish_cost_norm (XML name: dishCostNorm)
        value = getattr(self, "dish_cost_norm", None)
        if value is not None:  # Skip None values
            # Single element field: dish_cost_norm
            child_element = SubElement(element, "dishCostNorm")
            child_element.text = str(value)
            
        # Process field: dish_sale_price (XML name: dishSalePrice)
        value = getattr(self, "dish_sale_price", None)
        if value is not None:  # Skip None values
            # Single element field: dish_sale_price
            child_element = SubElement(element, "dishSalePrice")
            child_element.text = str(value)
            
        # Process field: hot_loss (XML name: hotLoss)
        value = getattr(self, "hot_loss", None)
        if value is not None:  # Skip None values
            # Single element field: hot_loss
            child_element = SubElement(element, "hotLoss")
            child_element.text = str(value)
            
        # Process field: item_id (XML name: itemId)
        value = getattr(self, "item_id", None)
        if value is not None:  # Skip None values
            # Single element field: item_id
            child_element = SubElement(element, "itemId")
            child_element.text = value
            
        # Process field: item_parent_id (XML name: itemParentId)
        value = getattr(self, "item_parent_id", None)
        if value is not None:  # Skip None values
            # Single element field: item_parent_id
            child_element = SubElement(element, "itemParentId")
            child_element.text = value
            
        # Process field: name (XML name: name)
        value = getattr(self, "name", None)
        if value is not None:  # Skip None values
            # Single element field: name
            child_element = SubElement(element, "name")
            child_element.text = value
            
        # Process field: num (XML name: num)
        value = getattr(self, "num", None)
        if value is not None:  # Skip None values
            # Single element field: num
            child_element = SubElement(element, "num")
            child_element.text = value
            
        # Process field: product (XML name: product)
        value = getattr(self, "product", None)
        if value is not None:  # Skip None values
            # Single element field: product
            child_element = SubElement(element, "product")
            child_element.text = value
            
        # Process field: product_in_dish_cost (XML name: productInDishCost)
        value = getattr(self, "product_in_dish_cost", None)
        if value is not None:  # Skip None values
            # Single element field: product_in_dish_cost
            child_element = SubElement(element, "productInDishCost")
            child_element.text = str(value)
            
        # Process field: source_product_cost_norm (XML name: sourceProductCostNorm)
        value = getattr(self, "source_product_cost_norm", None)
        if value is not None:  # Skip None values
            # Single element field: source_product_cost_norm
            child_element = SubElement(element, "sourceProductCostNorm")
            child_element.text = str(value)
            
        # Process field: tree_level (XML name: treeLevel)
        value = getattr(self, "tree_level", None)
        if value is not None:  # Skip None values
            # Single element field: tree_level
            child_element = SubElement(element, "treeLevel")
            child_element.text = str(value)
            
        # Process field: unit (XML name: unit)
        value = getattr(self, "unit", None)
        if value is not None:  # Skip None values
            # Single element field: unit
            child_element = SubElement(element, "unit")
            child_element.text = value
            


