# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikoserver_client.models.olap_filter import OlapFilter
from iikoserver_client.models.olap_v2_report_type_enum import OlapV2ReportTypeEnum
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class OlapV2Request(BaseModel):
    """
    OlapV2Request
    """ # noqa: E501
    report_type: OlapV2ReportTypeEnum = Field(alias="reportType")
    build_summary: Optional[StrictBool] = Field(default=False, description="Считать ли итоговые значения", alias="buildSummary")
    group_by_row_fields: List[StrictStr] = Field(description="Поля группировки по строкам", alias="groupByRowFields")
    group_by_col_fields: Optional[List[StrictStr]] = Field(default=None, description="Поля группировки по столбцам", alias="groupByColFields")
    aggregate_fields: List[StrictStr] = Field(description="Поля агрегации", alias="aggregateFields")
    filters: Optional[Dict[str, OlapFilter]] = Field(default=None, description="Фильтры отчета")
    __properties: ClassVar[List[str]] = ["reportType", "buildSummary", "groupByRowFields", "groupByColFields", "aggregateFields", "filters"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "OlapV2Request",
        
        
        "field_configs": {
            "report_type": {
                "xml_name": "reportType",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "build_summary": {
                "xml_name": "buildSummary",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "group_by_row_fields": {
                "xml_name": "groupByRowFields",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "group_by_col_fields": {
                "xml_name": "groupByColFields",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "aggregate_fields": {
                "xml_name": "aggregateFields",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "filters": {
                "xml_name": "filters",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OlapV2Request from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in filters (dict)
        _field_dict = {}
        if self.filters:
            for _key_filters in self.filters:
                if self.filters[_key_filters]:
                    _field_dict[_key_filters] = self.filters[_key_filters].to_dict()
            _dict['filters'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OlapV2Request from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reportType": obj.get("reportType"),
            "buildSummary": obj.get("buildSummary") if obj.get("buildSummary") is not None else False,
            "groupByRowFields": obj.get("groupByRowFields"),
            "groupByColFields": obj.get("groupByColFields"),
            "aggregateFields": obj.get("aggregateFields"),
            "filters": dict(
                (_k, OlapFilter.from_dict(_v))
                for _k, _v in obj["filters"].items()
            )
            if obj.get("filters") is not None
            else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of OlapV2Request from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of OlapV2Request from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: report_type (XML name: reportType)
        # Handle XML element: report_type
        # Single element field: report_type
        child_element = element.find("reportType")
        if child_element is not None:
            # Enum field
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["reportType"] = text_value
        
        # Process field: build_summary (XML name: buildSummary)
        # Handle XML element: build_summary
        # Single element field: build_summary
        child_element = element.find("buildSummary")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["buildSummary"] = text_value.lower() == 'true'
                
        
        # Process field: group_by_row_fields (XML name: groupByRowFields)
        # Handle XML element: group_by_row_fields
        # Array field: group_by_row_fields
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("groupByRowFields")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["groupByRowFields"] = items
        
        # Process field: group_by_col_fields (XML name: groupByColFields)
        # Handle XML element: group_by_col_fields
        # Array field: group_by_col_fields
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("groupByColFields")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["groupByColFields"] = items
        
        # Process field: aggregate_fields (XML name: aggregateFields)
        # Handle XML element: aggregate_fields
        # Array field: aggregate_fields
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("aggregateFields")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["aggregateFields"] = items
        
        # Process field: filters (XML name: filters)
        # Handle XML element: filters
        # Map field: filters (not commonly used in XML)
        # This is a simplified implementation
        child_elements = element.findall("filters")
        map_data = {}
        for child in child_elements:
            key = child.get('key') or child.tag
            value_obj = OlapFilter.from_xml_element(child)
            if value_obj is not None:
                map_data[key] = value_obj
        data["filters"] = map_data
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: report_type (XML name: reportType)
        value = getattr(self, "report_type", None)
        if value is not None:  # Skip None values
            # Single element field: report_type
            child_element = SubElement(element, "reportType")
            # Enum field
            child_element.text = str(value)
        # Process field: build_summary (XML name: buildSummary)
        value = getattr(self, "build_summary", None)
        if value is not None:  # Skip None values
            # Single element field: build_summary
            child_element = SubElement(element, "buildSummary")
            child_element.text = str(value).lower()
            
        # Process field: group_by_row_fields (XML name: groupByRowFields)
        value = getattr(self, "group_by_row_fields", None)
        if value is not None:  # Skip None values
            # Array field: group_by_row_fields
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "groupByRowFields")
                item_element.text = item
                
        # Process field: group_by_col_fields (XML name: groupByColFields)
        value = getattr(self, "group_by_col_fields", None)
        if value is not None:  # Skip None values
            # Array field: group_by_col_fields
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "groupByColFields")
                item_element.text = item
                
        # Process field: aggregate_fields (XML name: aggregateFields)
        value = getattr(self, "aggregate_fields", None)
        if value is not None:  # Skip None values
            # Array field: aggregate_fields
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "aggregateFields")
                item_element.text = item
                
        # Process field: filters (XML name: filters)
        value = getattr(self, "filters", None)
        if value is not None:  # Skip None values
            # Map field: filters (not commonly used in XML)
            # This is a simplified implementation
            for key, item in value.items():
                map_element = SubElement(element, "filters")
                map_element.set("key", key)
                if hasattr(item, "_to_xml_element_internal"):
                    item._to_xml_element_internal(map_element)


