# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from iikoserver_client.models.id_list_dto import IdListDto
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class ProductGroupDeleteRestoreRequestScheme(BaseModel):
    """
    ProductGroupDeleteRestoreRequestScheme
    """ # noqa: E501
    products: IdListDto
    product_groups: IdListDto = Field(alias="productGroups")
    __properties: ClassVar[List[str]] = ["products", "productGroups"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "ProductGroupDeleteRestoreRequestScheme",
        
        
        "field_configs": {
            "products": {
                "xml_name": "products",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "product_groups": {
                "xml_name": "productGroups",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductGroupDeleteRestoreRequestScheme from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of products
        if self.products:
            _dict['products'] = self.products.to_dict()
        # override the default output from pydantic by calling `to_dict()` of product_groups
        if self.product_groups:
            _dict['productGroups'] = self.product_groups.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductGroupDeleteRestoreRequestScheme from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "products": IdListDto.from_dict(obj["products"]) if obj.get("products") is not None else None,
            "productGroups": IdListDto.from_dict(obj["productGroups"]) if obj.get("productGroups") is not None else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of ProductGroupDeleteRestoreRequestScheme from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of ProductGroupDeleteRestoreRequestScheme from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: products (XML name: products)
        # Handle XML element: products
        # Single element field: products
        child_element = element.find("products")
        if child_element is not None:
            # Complex object field
            nested_obj = IdListDto.from_xml_element(child_element)
            if nested_obj is not None:
                data["products"] = nested_obj
        
        # Process field: product_groups (XML name: productGroups)
        # Handle XML element: product_groups
        # Single element field: product_groups
        child_element = element.find("productGroups")
        if child_element is not None:
            # Complex object field
            nested_obj = IdListDto.from_xml_element(child_element)
            if nested_obj is not None:
                data["productGroups"] = nested_obj
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: products (XML name: products)
        value = getattr(self, "products", None)
        if value is not None:  # Skip None values
            # Single element field: products
            child_element = SubElement(element, "products")
            # Complex object field
            if hasattr(value, "_to_xml_element_internal"):
                value._to_xml_element_internal(child_element)
        # Process field: product_groups (XML name: productGroups)
        value = getattr(self, "product_groups", None)
        if value is not None:  # Skip None values
            # Single element field: product_groups
            child_element = SubElement(element, "productGroups")
            # Complex object field
            if hasattr(value, "_to_xml_element_internal"):
                value._to_xml_element_internal(child_element)


