# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikoserver_client.models.payment_details_xml import PaymentDetailsXml
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class ScheduleXml(BaseModel):
    """
    ScheduleXml
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Идентификатор смены (при создании может быть не заполнено)")
    employee_id: StrictStr = Field(description="Идентификатор сотрудника", alias="employeeId")
    role_id: Optional[StrictStr] = Field(default=None, description="Должность, на которую назначена смена сотруднику", alias="roleId")
    non_paid_minutes: Optional[StrictInt] = Field(default=0, description="Неоплачиваемое время смены (например, время на обеденный перерыв)", alias="nonPaidMinutes")
    schedule_type_id: Optional[StrictStr] = Field(default=None, description="Идентификатор типа смены", alias="scheduleTypeId")
    schedule_type_code: Optional[StrictStr] = Field(default=None, description="Код типа смены", alias="scheduleTypeCode")
    date_from: Optional[StrictStr] = Field(default=None, description="Дата и время начала смены", alias="dateFrom")
    date_to: Optional[StrictStr] = Field(default=None, description="Дата и время окончания смены", alias="dateTo")
    department_id: StrictStr = Field(description="Идентификатор подразделения", alias="departmentId")
    department_name: StrictStr = Field(description="Название подразделения", alias="departmentName")
    payment_details: Optional[PaymentDetailsXml] = Field(default=None, alias="paymentDetails")
    __properties: ClassVar[List[str]] = ["id", "employeeId", "roleId", "nonPaidMinutes", "scheduleTypeId", "scheduleTypeCode", "dateFrom", "dateTo", "departmentId", "departmentName", "paymentDetails"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "schedule",
        
        
        "field_configs": {
            "id": {
                "xml_name": "id",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "employee_id": {
                "xml_name": "employeeId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "role_id": {
                "xml_name": "roleId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "non_paid_minutes": {
                "xml_name": "nonPaidMinutes",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "schedule_type_id": {
                "xml_name": "scheduleTypeId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "schedule_type_code": {
                "xml_name": "scheduleTypeCode",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "date_from": {
                "xml_name": "dateFrom",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "date_to": {
                "xml_name": "dateTo",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "department_id": {
                "xml_name": "departmentId",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "department_name": {
                "xml_name": "departmentName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "payment_details": {
                "xml_name": "paymentDetails",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleXml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of payment_details
        if self.payment_details:
            _dict['paymentDetails'] = self.payment_details.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if role_id (nullable) is None
        # and model_fields_set contains the field
        if self.role_id is None and "role_id" in self.model_fields_set:
            _dict['roleId'] = None

        # set to None if schedule_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_type_id is None and "schedule_type_id" in self.model_fields_set:
            _dict['scheduleTypeId'] = None

        # set to None if schedule_type_code (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_type_code is None and "schedule_type_code" in self.model_fields_set:
            _dict['scheduleTypeCode'] = None

        # set to None if date_from (nullable) is None
        # and model_fields_set contains the field
        if self.date_from is None and "date_from" in self.model_fields_set:
            _dict['dateFrom'] = None

        # set to None if date_to (nullable) is None
        # and model_fields_set contains the field
        if self.date_to is None and "date_to" in self.model_fields_set:
            _dict['dateTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleXml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "employeeId": obj.get("employeeId"),
            "roleId": obj.get("roleId"),
            "nonPaidMinutes": obj.get("nonPaidMinutes") if obj.get("nonPaidMinutes") is not None else 0,
            "scheduleTypeId": obj.get("scheduleTypeId"),
            "scheduleTypeCode": obj.get("scheduleTypeCode"),
            "dateFrom": obj.get("dateFrom"),
            "dateTo": obj.get("dateTo"),
            "departmentId": obj.get("departmentId"),
            "departmentName": obj.get("departmentName"),
            "paymentDetails": PaymentDetailsXml.from_dict(obj["paymentDetails"]) if obj.get("paymentDetails") is not None else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of ScheduleXml from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of ScheduleXml from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: id (XML name: id)
        # Handle XML element: id
        # Single element field: id
        child_element = element.find("id")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["id"] = text_value
                
        
        # Process field: employee_id (XML name: employeeId)
        # Handle XML element: employee_id
        # Single element field: employee_id
        child_element = element.find("employeeId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["employeeId"] = text_value
                
        
        # Process field: role_id (XML name: roleId)
        # Handle XML element: role_id
        # Single element field: role_id
        child_element = element.find("roleId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["roleId"] = text_value
                
        
        # Process field: non_paid_minutes (XML name: nonPaidMinutes)
        # Handle XML element: non_paid_minutes
        # Single element field: non_paid_minutes
        child_element = element.find("nonPaidMinutes")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["nonPaidMinutes"] = int(text_value)
                except ValueError:
                    data["nonPaidMinutes"] = text_value
                
        
        # Process field: schedule_type_id (XML name: scheduleTypeId)
        # Handle XML element: schedule_type_id
        # Single element field: schedule_type_id
        child_element = element.find("scheduleTypeId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["scheduleTypeId"] = text_value
                
        
        # Process field: schedule_type_code (XML name: scheduleTypeCode)
        # Handle XML element: schedule_type_code
        # Single element field: schedule_type_code
        child_element = element.find("scheduleTypeCode")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["scheduleTypeCode"] = text_value
                
        
        # Process field: date_from (XML name: dateFrom)
        # Handle XML element: date_from
        # Single element field: date_from
        child_element = element.find("dateFrom")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["dateFrom"] = text_value
                
        
        # Process field: date_to (XML name: dateTo)
        # Handle XML element: date_to
        # Single element field: date_to
        child_element = element.find("dateTo")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["dateTo"] = text_value
                
        
        # Process field: department_id (XML name: departmentId)
        # Handle XML element: department_id
        # Single element field: department_id
        child_element = element.find("departmentId")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["departmentId"] = text_value
                
        
        # Process field: department_name (XML name: departmentName)
        # Handle XML element: department_name
        # Single element field: department_name
        child_element = element.find("departmentName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["departmentName"] = text_value
                
        
        # Process field: payment_details (XML name: paymentDetails)
        # Handle XML element: payment_details
        # Single element field: payment_details
        child_element = element.find("paymentDetails")
        if child_element is not None:
            # Complex object field
            nested_obj = PaymentDetailsXml.from_xml_element(child_element)
            if nested_obj is not None:
                data["paymentDetails"] = nested_obj
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: id (XML name: id)
        value = getattr(self, "id", None)
        if value is not None:  # Skip None values
            # Single element field: id
            child_element = SubElement(element, "id")
            child_element.text = value
            
        # Process field: employee_id (XML name: employeeId)
        value = getattr(self, "employee_id", None)
        if value is not None:  # Skip None values
            # Single element field: employee_id
            child_element = SubElement(element, "employeeId")
            child_element.text = value
            
        # Process field: role_id (XML name: roleId)
        value = getattr(self, "role_id", None)
        if value is not None:  # Skip None values
            # Single element field: role_id
            child_element = SubElement(element, "roleId")
            child_element.text = value
            
        # Process field: non_paid_minutes (XML name: nonPaidMinutes)
        value = getattr(self, "non_paid_minutes", None)
        if value is not None:  # Skip None values
            # Single element field: non_paid_minutes
            child_element = SubElement(element, "nonPaidMinutes")
            child_element.text = str(value)
            
        # Process field: schedule_type_id (XML name: scheduleTypeId)
        value = getattr(self, "schedule_type_id", None)
        if value is not None:  # Skip None values
            # Single element field: schedule_type_id
            child_element = SubElement(element, "scheduleTypeId")
            child_element.text = value
            
        # Process field: schedule_type_code (XML name: scheduleTypeCode)
        value = getattr(self, "schedule_type_code", None)
        if value is not None:  # Skip None values
            # Single element field: schedule_type_code
            child_element = SubElement(element, "scheduleTypeCode")
            child_element.text = value
            
        # Process field: date_from (XML name: dateFrom)
        value = getattr(self, "date_from", None)
        if value is not None:  # Skip None values
            # Single element field: date_from
            child_element = SubElement(element, "dateFrom")
            child_element.text = value
            
        # Process field: date_to (XML name: dateTo)
        value = getattr(self, "date_to", None)
        if value is not None:  # Skip None values
            # Single element field: date_to
            child_element = SubElement(element, "dateTo")
            child_element.text = value
            
        # Process field: department_id (XML name: departmentId)
        value = getattr(self, "department_id", None)
        if value is not None:  # Skip None values
            # Single element field: department_id
            child_element = SubElement(element, "departmentId")
            child_element.text = value
            
        # Process field: department_name (XML name: departmentName)
        value = getattr(self, "department_name", None)
        if value is not None:  # Skip None values
            # Single element field: department_name
            child_element = SubElement(element, "departmentName")
            child_element.text = value
            
        # Process field: payment_details (XML name: paymentDetails)
        value = getattr(self, "payment_details", None)
        if value is not None:  # Skip None values
            # Single element field: payment_details
            child_element = SubElement(element, "paymentDetails")
            # Complex object field
            if hasattr(value, "_to_xml_element_internal"):
                value._to_xml_element_internal(child_element)


