# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from iikoserver_client.models.container_dto_xml import ContainerDtoXml
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class SupplierPriceListItemDtoXml(BaseModel):
    """
    SupplierPriceListItemDtoXml
    """ # noqa: E501
    native_product: Optional[StrictStr] = Field(default=None, description="Товар у нас (guid)", alias="nativeProduct")
    native_product_code: Optional[StrictStr] = Field(default=None, description="Код товара у нас", alias="nativeProductCode")
    native_product_num: Optional[StrictStr] = Field(default=None, description="Артикул товара у нас", alias="nativeProductNum")
    native_product_name: Optional[StrictStr] = Field(default=None, description="Название товара у нас", alias="nativeProductName")
    supplier_product: Optional[StrictStr] = Field(default=None, description="Товар у поставщика (guid)", alias="supplierProduct")
    supplier_product_code: Optional[StrictStr] = Field(default=None, description="Код товара у поставщика", alias="supplierProductCode")
    supplier_product_num: Optional[StrictStr] = Field(default=None, description="Артикул товара у поставщика", alias="supplierProductNum")
    supplier_product_name: Optional[StrictStr] = Field(default=None, description="Название товара у поставщика", alias="supplierProductName")
    cost_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Стоимость товара", alias="costPrice")
    allowable_price_deviation: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Допустимое отклонение от цены (%)", alias="allowablePriceDeviation")
    container: Optional[ContainerDtoXml] = None
    __properties: ClassVar[List[str]] = ["nativeProduct", "nativeProductCode", "nativeProductNum", "nativeProductName", "supplierProduct", "supplierProductCode", "supplierProductNum", "supplierProductName", "costPrice", "allowablePriceDeviation", "container"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "supplierPriceListItemDto",
        
        
        "field_configs": {
            "native_product": {
                "xml_name": "nativeProduct",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "native_product_code": {
                "xml_name": "nativeProductCode",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "native_product_num": {
                "xml_name": "nativeProductNum",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "native_product_name": {
                "xml_name": "nativeProductName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "supplier_product": {
                "xml_name": "supplierProduct",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "supplier_product_code": {
                "xml_name": "supplierProductCode",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "supplier_product_num": {
                "xml_name": "supplierProductNum",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "supplier_product_name": {
                "xml_name": "supplierProductName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "cost_price": {
                "xml_name": "costPrice",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "allowable_price_deviation": {
                "xml_name": "allowablePriceDeviation",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "container": {
                "xml_name": "containerDto",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SupplierPriceListItemDtoXml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of container
        if self.container:
            _dict['container'] = self.container.to_dict()
        # set to None if native_product (nullable) is None
        # and model_fields_set contains the field
        if self.native_product is None and "native_product" in self.model_fields_set:
            _dict['nativeProduct'] = None

        # set to None if native_product_code (nullable) is None
        # and model_fields_set contains the field
        if self.native_product_code is None and "native_product_code" in self.model_fields_set:
            _dict['nativeProductCode'] = None

        # set to None if native_product_num (nullable) is None
        # and model_fields_set contains the field
        if self.native_product_num is None and "native_product_num" in self.model_fields_set:
            _dict['nativeProductNum'] = None

        # set to None if native_product_name (nullable) is None
        # and model_fields_set contains the field
        if self.native_product_name is None and "native_product_name" in self.model_fields_set:
            _dict['nativeProductName'] = None

        # set to None if supplier_product (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_product is None and "supplier_product" in self.model_fields_set:
            _dict['supplierProduct'] = None

        # set to None if supplier_product_code (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_product_code is None and "supplier_product_code" in self.model_fields_set:
            _dict['supplierProductCode'] = None

        # set to None if supplier_product_num (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_product_num is None and "supplier_product_num" in self.model_fields_set:
            _dict['supplierProductNum'] = None

        # set to None if supplier_product_name (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_product_name is None and "supplier_product_name" in self.model_fields_set:
            _dict['supplierProductName'] = None

        # set to None if cost_price (nullable) is None
        # and model_fields_set contains the field
        if self.cost_price is None and "cost_price" in self.model_fields_set:
            _dict['costPrice'] = None

        # set to None if allowable_price_deviation (nullable) is None
        # and model_fields_set contains the field
        if self.allowable_price_deviation is None and "allowable_price_deviation" in self.model_fields_set:
            _dict['allowablePriceDeviation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SupplierPriceListItemDtoXml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nativeProduct": obj.get("nativeProduct"),
            "nativeProductCode": obj.get("nativeProductCode"),
            "nativeProductNum": obj.get("nativeProductNum"),
            "nativeProductName": obj.get("nativeProductName"),
            "supplierProduct": obj.get("supplierProduct"),
            "supplierProductCode": obj.get("supplierProductCode"),
            "supplierProductNum": obj.get("supplierProductNum"),
            "supplierProductName": obj.get("supplierProductName"),
            "costPrice": obj.get("costPrice"),
            "allowablePriceDeviation": obj.get("allowablePriceDeviation"),
            "container": ContainerDtoXml.from_dict(obj["container"]) if obj.get("container") is not None else None
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of SupplierPriceListItemDtoXml from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of SupplierPriceListItemDtoXml from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: native_product (XML name: nativeProduct)
        # Handle XML element: native_product
        # Single element field: native_product
        child_element = element.find("nativeProduct")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["nativeProduct"] = text_value
                
        
        # Process field: native_product_code (XML name: nativeProductCode)
        # Handle XML element: native_product_code
        # Single element field: native_product_code
        child_element = element.find("nativeProductCode")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["nativeProductCode"] = text_value
                
        
        # Process field: native_product_num (XML name: nativeProductNum)
        # Handle XML element: native_product_num
        # Single element field: native_product_num
        child_element = element.find("nativeProductNum")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["nativeProductNum"] = text_value
                
        
        # Process field: native_product_name (XML name: nativeProductName)
        # Handle XML element: native_product_name
        # Single element field: native_product_name
        child_element = element.find("nativeProductName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["nativeProductName"] = text_value
                
        
        # Process field: supplier_product (XML name: supplierProduct)
        # Handle XML element: supplier_product
        # Single element field: supplier_product
        child_element = element.find("supplierProduct")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["supplierProduct"] = text_value
                
        
        # Process field: supplier_product_code (XML name: supplierProductCode)
        # Handle XML element: supplier_product_code
        # Single element field: supplier_product_code
        child_element = element.find("supplierProductCode")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["supplierProductCode"] = text_value
                
        
        # Process field: supplier_product_num (XML name: supplierProductNum)
        # Handle XML element: supplier_product_num
        # Single element field: supplier_product_num
        child_element = element.find("supplierProductNum")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["supplierProductNum"] = text_value
                
        
        # Process field: supplier_product_name (XML name: supplierProductName)
        # Handle XML element: supplier_product_name
        # Single element field: supplier_product_name
        child_element = element.find("supplierProductName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["supplierProductName"] = text_value
                
        
        # Process field: cost_price (XML name: costPrice)
        # Handle XML element: cost_price
        # Single element field: cost_price
        child_element = element.find("costPrice")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["costPrice"] = float(text_value)
                except ValueError:
                    data["costPrice"] = text_value
                
        
        # Process field: allowable_price_deviation (XML name: allowablePriceDeviation)
        # Handle XML element: allowable_price_deviation
        # Single element field: allowable_price_deviation
        child_element = element.find("allowablePriceDeviation")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["allowablePriceDeviation"] = float(text_value)
                except ValueError:
                    data["allowablePriceDeviation"] = text_value
                
        
        # Process field: container (XML name: containerDto)
        # Handle XML element: container
        # Single element field: container
        child_element = element.find("containerDto")
        if child_element is not None:
            # Complex object field
            nested_obj = ContainerDtoXml.from_xml_element(child_element)
            if nested_obj is not None:
                data["container"] = nested_obj
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: native_product (XML name: nativeProduct)
        value = getattr(self, "native_product", None)
        if value is not None:  # Skip None values
            # Single element field: native_product
            child_element = SubElement(element, "nativeProduct")
            child_element.text = value
            
        # Process field: native_product_code (XML name: nativeProductCode)
        value = getattr(self, "native_product_code", None)
        if value is not None:  # Skip None values
            # Single element field: native_product_code
            child_element = SubElement(element, "nativeProductCode")
            child_element.text = value
            
        # Process field: native_product_num (XML name: nativeProductNum)
        value = getattr(self, "native_product_num", None)
        if value is not None:  # Skip None values
            # Single element field: native_product_num
            child_element = SubElement(element, "nativeProductNum")
            child_element.text = value
            
        # Process field: native_product_name (XML name: nativeProductName)
        value = getattr(self, "native_product_name", None)
        if value is not None:  # Skip None values
            # Single element field: native_product_name
            child_element = SubElement(element, "nativeProductName")
            child_element.text = value
            
        # Process field: supplier_product (XML name: supplierProduct)
        value = getattr(self, "supplier_product", None)
        if value is not None:  # Skip None values
            # Single element field: supplier_product
            child_element = SubElement(element, "supplierProduct")
            child_element.text = value
            
        # Process field: supplier_product_code (XML name: supplierProductCode)
        value = getattr(self, "supplier_product_code", None)
        if value is not None:  # Skip None values
            # Single element field: supplier_product_code
            child_element = SubElement(element, "supplierProductCode")
            child_element.text = value
            
        # Process field: supplier_product_num (XML name: supplierProductNum)
        value = getattr(self, "supplier_product_num", None)
        if value is not None:  # Skip None values
            # Single element field: supplier_product_num
            child_element = SubElement(element, "supplierProductNum")
            child_element.text = value
            
        # Process field: supplier_product_name (XML name: supplierProductName)
        value = getattr(self, "supplier_product_name", None)
        if value is not None:  # Skip None values
            # Single element field: supplier_product_name
            child_element = SubElement(element, "supplierProductName")
            child_element.text = value
            
        # Process field: cost_price (XML name: costPrice)
        value = getattr(self, "cost_price", None)
        if value is not None:  # Skip None values
            # Single element field: cost_price
            child_element = SubElement(element, "costPrice")
            child_element.text = str(value)
            
        # Process field: allowable_price_deviation (XML name: allowablePriceDeviation)
        value = getattr(self, "allowable_price_deviation", None)
        if value is not None:  # Skip None values
            # Single element field: allowable_price_deviation
            child_element = SubElement(element, "allowablePriceDeviation")
            child_element.text = str(value)
            
        # Process field: container (XML name: containerDto)
        value = getattr(self, "container", None)
        if value is not None:  # Skip None values
            # Single element field: container
            child_element = SubElement(element, "containerDto")
            # Complex object field
            if hasattr(value, "_to_xml_element_internal"):
                value._to_xml_element_internal(child_element)


