# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikoserver_client.models.id_name_dto import IdNameDto
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class TerminalDtoXml(BaseModel):
    """
    TerminalDtoXml
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for the terminal.")
    name: StrictStr = Field(description="Name of the terminal.")
    computer_name: Optional[StrictStr] = Field(default=None, description="Name of the computer associated with the terminal.", alias="computerName")
    anonymous: StrictBool = Field(description="Indicates if the terminal is anonymous.")
    group_info: Optional[IdNameDto] = Field(default=None, alias="groupInfo")
    restaurant_section_ids: Optional[List[StrictStr]] = Field(description="List of restaurant section IDs.", alias="restaurantSectionIds")
    __properties: ClassVar[List[str]] = ["id", "name", "computerName", "anonymous", "groupInfo", "restaurantSectionIds"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "terminalDto",
        
        
        "field_configs": {
            "id": {
                "xml_name": "id",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "name": {
                "xml_name": "name",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "computer_name": {
                "xml_name": "computerName",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "anonymous": {
                "xml_name": "anonymous",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "group_info": {
                "xml_name": "groupInfo",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "restaurant_section_ids": {
                "xml_name": "restaurantSectionIds",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TerminalDtoXml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of group_info
        if self.group_info:
            _dict['groupInfo'] = self.group_info.to_dict()
        # set to None if computer_name (nullable) is None
        # and model_fields_set contains the field
        if self.computer_name is None and "computer_name" in self.model_fields_set:
            _dict['computerName'] = None

        # set to None if restaurant_section_ids (nullable) is None
        # and model_fields_set contains the field
        if self.restaurant_section_ids is None and "restaurant_section_ids" in self.model_fields_set:
            _dict['restaurantSectionIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TerminalDtoXml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "computerName": obj.get("computerName"),
            "anonymous": obj.get("anonymous"),
            "groupInfo": IdNameDto.from_dict(obj["groupInfo"]) if obj.get("groupInfo") is not None else None,
            "restaurantSectionIds": obj.get("restaurantSectionIds")
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of TerminalDtoXml from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of TerminalDtoXml from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: id (XML name: id)
        # Handle XML element: id
        # Single element field: id
        child_element = element.find("id")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["id"] = text_value
                
        
        # Process field: name (XML name: name)
        # Handle XML element: name
        # Single element field: name
        child_element = element.find("name")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["name"] = text_value
                
        
        # Process field: computer_name (XML name: computerName)
        # Handle XML element: computer_name
        # Single element field: computer_name
        child_element = element.find("computerName")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["computerName"] = text_value
                
        
        # Process field: anonymous (XML name: anonymous)
        # Handle XML element: anonymous
        # Single element field: anonymous
        child_element = element.find("anonymous")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["anonymous"] = text_value.lower() == 'true'
                
        
        # Process field: group_info (XML name: groupInfo)
        # Handle XML element: group_info
        # Single element field: group_info
        child_element = element.find("groupInfo")
        if child_element is not None:
            # Complex object field
            nested_obj = IdNameDto.from_xml_element(child_element)
            if nested_obj is not None:
                data["groupInfo"] = nested_obj
        
        # Process field: restaurant_section_ids (XML name: restaurantSectionIds)
        # Handle XML element: restaurant_section_ids
        # Array field: restaurant_section_ids
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("restaurantSectionIds")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["restaurantSectionIds"] = items
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: id (XML name: id)
        value = getattr(self, "id", None)
        if value is not None:  # Skip None values
            # Single element field: id
            child_element = SubElement(element, "id")
            child_element.text = value
            
        # Process field: name (XML name: name)
        value = getattr(self, "name", None)
        if value is not None:  # Skip None values
            # Single element field: name
            child_element = SubElement(element, "name")
            child_element.text = value
            
        # Process field: computer_name (XML name: computerName)
        value = getattr(self, "computer_name", None)
        if value is not None:  # Skip None values
            # Single element field: computer_name
            child_element = SubElement(element, "computerName")
            child_element.text = value
            
        # Process field: anonymous (XML name: anonymous)
        value = getattr(self, "anonymous", None)
        if value is not None:  # Skip None values
            # Single element field: anonymous
            child_element = SubElement(element, "anonymous")
            child_element.text = str(value).lower()
            
        # Process field: group_info (XML name: groupInfo)
        value = getattr(self, "group_info", None)
        if value is not None:  # Skip None values
            # Single element field: group_info
            child_element = SubElement(element, "groupInfo")
            # Complex object field
            if hasattr(value, "_to_xml_element_internal"):
                value._to_xml_element_internal(child_element)
        # Process field: restaurant_section_ids (XML name: restaurantSectionIds)
        value = getattr(self, "restaurant_section_ids", None)
        if value is not None:  # Skip None values
            # Array field: restaurant_section_ids
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "restaurantSectionIds")
                item_element.text = item
                


