# coding: utf-8

"""
    iikoServer API

    API Server позволяет сделать интеграции, которые предназначены для работы с номенклатурой, отчетами, документами, данными сотрудников и приказами.   ### Ограничения и рекомендации - Запросы должны выполняться последовательно друг за другом - Запрашивайте данные за период не длиннее одного месяца, в идеале — за один день или неделю - Для OLAPv2-отчетов рекомендуется устанавливать build-summary=false - При построении OLAPv2-отчета рекомендуется использовать не более 7 полей - Перед выполнением запросов проверяйте их на демо сервере

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set, Union
from typing_extensions import Self

# XML support imports
from lxml import etree
from lxml.etree import Element, SubElement

class V2EntitiesProductsCategoryListPostRequest(BaseModel):
    """
    V2EntitiesProductsCategoryListPostRequest
    """ # noqa: E501
    include_deleted: Optional[StrictBool] = Field(default=False, description="Включать ли в результат удаленные элементы", alias="includeDeleted")
    ids: Optional[List[StrictStr]] = Field(default=None, description="Возвращаемые элементы должны иметь id из этого списка")
    revision_from: Optional[StrictInt] = Field(default=-1, description="Номер ревизии, начиная с которой необходимо отфильтровать сущности. Не включающий саму ревизию, т.е. ревизия объекта > revisionFrom", alias="revisionFrom")
    __properties: ClassVar[List[str]] = ["includeDeleted", "ids", "revisionFrom"]
    
    # XML metadata for the class
    __xml_config: ClassVar[Dict[str, Any]] = {
        "root_name": "V2EntitiesProductsCategoryListPostRequest",
        
        
        "field_configs": {
            "include_deleted": {
                "xml_name": "includeDeleted",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "ids": {
                "xml_name": "ids",
                
                
                "is_attribute": False,
                "is_wrapped": False
            },
            "revision_from": {
                "xml_name": "revisionFrom",
                
                
                "is_attribute": False,
                "is_wrapped": False
            }
        }
    }


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V2EntitiesProductsCategoryListPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V2EntitiesProductsCategoryListPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "includeDeleted": obj.get("includeDeleted") if obj.get("includeDeleted") is not None else False,
            "ids": obj.get("ids"),
            "revisionFrom": obj.get("revisionFrom") if obj.get("revisionFrom") is not None else -1
        })
        return _obj



    @classmethod
    def from_xml(cls, xml_str: str) -> Optional[Self]:
        """Create an instance of V2EntitiesProductsCategoryListPostRequest from an XML string"""
        try:
            if isinstance(xml_str, str):
                xml_str = xml_str.encode('utf-8')
            root = etree.fromstring(xml_str)
            return cls.from_xml_element(root)
        except Exception as e:
            raise ValueError(f"Failed to parse XML: {e}")

    @classmethod
    def from_xml_element(cls, element: Element) -> Optional[Self]:
        """Create an instance of V2EntitiesProductsCategoryListPostRequest from an XML element"""
        return cls._from_xml_element_internal(element)

    @classmethod
    def _from_xml_element_internal(cls, element: Element) -> Optional[Self]:
        """Internal method to create instance from XML element"""
        if element is None:
            return None

        data = {}
        
        # Process field: include_deleted (XML name: includeDeleted)
        # Handle XML element: include_deleted
        # Single element field: include_deleted
        child_element = element.find("includeDeleted")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                data["includeDeleted"] = text_value.lower() == 'true'
                
        
        # Process field: ids (XML name: ids)
        # Handle XML element: ids
        # Array field: ids
        # Non-wrapped array - direct elements
        # Primitive items in non-wrapped array
        child_elements = element.findall("ids")
        items = []
        for child in child_elements:
            text_value = child.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                items.append(text_value)
                
        data["ids"] = items
        
        # Process field: revision_from (XML name: revisionFrom)
        # Handle XML element: revision_from
        # Single element field: revision_from
        child_element = element.find("revisionFrom")
        if child_element is not None:
            # Check for null or empty values
            text_value = child_element.text
            if text_value is not None and text_value.strip() != "" and text_value != "null":
                try:
                    data["revisionFrom"] = int(text_value)
                except ValueError:
                    data["revisionFrom"] = text_value
                
        
        
        return cls.from_dict(data)

    def to_xml(self) -> str:
        """Create an XML string representation of the model"""
        root_element = Element(self.__xml_config.get("root_name", self.__class__.__name__))
        
        # Populate the XML element with model data
        self._to_xml_element_internal(root_element)
        
        # Convert to string with XML declaration
        return etree.tostring(root_element, encoding="utf-8", pretty_print=True, xml_declaration=True).decode("utf-8")

    def _to_xml_element_internal(self, element: Element) -> None:
        """Internal method to populate an XML element with model data"""
        
        # Process field: include_deleted (XML name: includeDeleted)
        value = getattr(self, "include_deleted", None)
        if value is not None:  # Skip None values
            # Single element field: include_deleted
            child_element = SubElement(element, "includeDeleted")
            child_element.text = str(value).lower()
            
        # Process field: ids (XML name: ids)
        value = getattr(self, "ids", None)
        if value is not None:  # Skip None values
            # Array field: ids
            # Non-wrapped array - add elements directly
            for item in value:
                # Primitive items in non-wrapped array
                item_element = SubElement(element, "ids")
                item_element.text = item
                
        # Process field: revision_from (XML name: revisionFrom)
        value = getattr(self, "revision_from", None)
        if value is not None:  # Skip None values
            # Single element field: revision_from
            child_element = SubElement(element, "revisionFrom")
            child_element.text = str(value)
            


